### ISSUE TITLE
token transfer fails for 0.42 and 0.43

### ISSUE THREAD

**Issue by t4sk** [FuelLabs/fuels-rs#1007]
A simple token transfer fails for versions 0.42 and 0.43. It works fine for 0.41. Is this a bug in the SDK?

Here is the code running 0.41. 
https://github.com/t4sk/hello-sway/tree/main/test-token-transfer

My tests fails after I switched to 0.42 inside `Cargo.toml`.

Here is the contract
https://github.com/t4sk/hello-sway/blob/ad016e05edb4c7c0b5afe37c1f8f05879ab7fcd6/test-token-transfer/src/main.sw#L19-L21

Here is the test
https://github.com/t4sk/hello-sway/blob/ad016e05edb4c7c0b5afe37c1f8f05879ab7fcd6/test-token-transfer/tests/harness.rs#L63-L69

**Comment by iqdecay** [comment]
It looks like you are not using the right `fuel-core` version. The `0.42` and `0.43` versions of the SDK are supposed to work with `fuel-core 0.18`. Can you double check that you are using those versions?

**Comment by t4sk** [comment]
Yup I was testing with beta-3 settings.
Typing `fuelup default latest` fixed it.
Thanks
