### ISSUE TITLE
feat: support `String` type from `sway-libs`

### ISSUE THREAD

**Issue by iqdecay** [FuelLabs/fuels-rs#1011]
The [sway std-lib crate](https://github.com/FuelLabs/sway/blob/master/sway-lib-std/src/string.sw) added support for dynamically-sized string types, we should support it as a type in the SDK.

**Comment by digorithm** [comment]
Note that we already support Sway's _statically_ sized strings. (https://rust.fuel.network/v0.43.0/types/string.html) but this issue is specifically for the new Sway's dynamic string type.
