### ISSUE TITLE
Investigate why some errors at the fuel-core / fuel-vm level aren’t being captured by the SDK

### ISSUE THREAD

**Issue by vnepveu** [FuelLabs/fuels-rs#102]
Sometimes, some errors do not get captured at all by the SDK. For an example of that, see branch https://github.com/FuelLabs/fuels-rs/tree/repro-storage-slots where the 2nd transaction is actually a reverting transaction with `MemoryOverflow` error, and nothing appears in the receipts.

**Comment by digorithm** [comment]
Update on this: use https://github.com/FuelLabs/fuel-core/blob/master/fuel-client/src/client.rs#L166 at https://github.com/FuelLabs/fuels-rs/blob/eb0f17c5907cb17b54c302f60283ea4f8f483605/fuels-contract/src/script.rs 

```rust
 pub async fn call(self, fuel_client: &FuelClient) -> Result<Vec<Receipt>, Error> {
    let tx_id = fuel_client.submit(&self.tx).await.unwrap();

    let receipts = fuel_client.receipts(&tx_id.0.to_string()).await.unwrap();

    Ok(receipts)
}
```

If `value == 0` and `receipts.len() == 0`. This way we should be able to get the reason of the failed transaction and bubble it up to the user.
