### ISSUE TITLE
Investigate weird `MemoryOverflow` error

### ISSUE THREAD

**Issue by vnepveu** [FuelLabs/fuels-rs#104]
Context: trying to run the exact same very simple contract (that just sets a storage slots to a certain value) gives out different results depending on the storage address used. The invalid result yield a `MemoryOverflow` error.
Did some more testing: 
- Let `(pos, val)` represent a storage key where byte in position  `pos` has value `val` (it follows that `pos` is in [0,31] and `value` in [0,255]).
- Then :
```
( pos is in [0,4] && val is in [1,255]) || (pos == 5 && val is in [128,255])
<=>
MemoryOverflow
```

You can find a repro on branch https://github.com/FuelLabs/fuels-rs/tree/repro-storage-slots. Run `cargo test storage -- --show-output`.

**Comment by adlerjohn** [comment]
`MemoryOverflow` is a bit sus, because it has nothing to do with storage. It means you're trying to access _memory_ larger than the maximum size. This might have to do with the compiler too, if it points to the wrong memory address. cc @sezna for triaging as well.

**Comment by vnepveu** [comment]
Update: created a new testcase with another `MemoryOverflow` where just returning a B256 passed as argument fails with memory overflow. 
Testcase: https://github.com/FuelLabs/fuels-rs/blob/c4b8ba6137b7d195337860178c30ead72835d448/fuels-abigen-macro/tests/harness.rs#L1441

**Comment by vnepveu** [comment]
Update: reformulated the bug after running an extensive search on the `(pos,val)` tuple.

**Comment by digorithm** [comment]
@vnepveu What's the current situation with this issue? Is it still a problem? And if it is, are you still working on it?

**Comment by vnepveu** [comment]
I can check if it's still alive with the current versions. If it is, I will move the issue to `Sway` with some additional investigation know that I can read a bit of ASM.

**Comment by vnepveu** [comment]
Spent quite some time updating the repro, cannot reproduce the bug! Closing.
