### ISSUE TITLE
Add `Vec` type

### ISSUE THREAD

**Issue by emilyaherbert** [FuelLabs/fuels-rs#107]
I've found myself wanting to use the equivalent of Rust's `Vec` when writing Sway code. I'd like to see this implemented in the SDK 😄 

This probably is dependent on this issue: https://github.com/FuelLabs/sway/issues/428

**Comment by emilyaherbert** [comment]
Something like: https://doc.rust-lang.org/std/vec/struct.Vec.html

**Comment by digorithm** [comment]
Hmm, doesn't the SDK already support vectors? Although only static/fixed size vectors. I remember implementing it a while ago. I.e. if you declare a Sway struct with a fixed-size vector as one of its properties, and use this struct as input in your ABI method, it _should_ work fine 🤔

I'm imagining that that's what you're looking for? Sorry if it's not and it's something entirely different!

**Comment by emilyaherbert** [comment]
Oops haha @digorithm this proposal probably has you confused because I meant to post it in https://github.com/FuelLabs/sway-lib-std 😅

**Comment by digorithm** [comment]
Hahaha that makes a whole lot more sense!
