### ISSUE TITLE
Abigen support for tuple return values

### ISSUE THREAD

**Issue by simonr0204** [FuelLabs/fuels-rs#108]
`abigen!` panics with :

`error: proc macro panicked
...
  = help: message: called Result::unwrap() on an Err value: MissingData("cannot parse custom type with no components")`
 
 when parsing an ABI containing functions which return tuples, e.g. 
 
 ` fn my_tuple_function(gas_: u64, amount_: u64, asset_id_: b256, params: () ) -> (u64, u64);`

**Comment by vnepveu** [comment]
So after trying a few things (experiences can be found at https://github.com/FuelLabs/fuels-rs/tree/vnepveu/feat-support-tuple-type):
- The "major" blocker for this PR is the "no-orphans" rule of Rust.

Basically, by definition, a tuple is a _foreign type_. And the thing with _foreign types_ is that you can implement only traits that are defined **in the current crate**. Issue being that we need to implement the `Tokenizable` trait, which is defined in a particular crate (`fuels-core` but that's not the issue). 
Passing it over to @digorithm.

A solution I've observed, but is very complicated, in `ethers-rs`: https://github.com/gakonst/ethers-rs/blob/78c87b11269fe94da6d09a04035afd8367fd3ae5/ethers-core/src/abi/tokens.rs#L79.
