### ISSUE TITLE
Fix support for arrays

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/fuels-rs#111]
The SDK had support for static non-string arrays when the format was `T[n]` as specified here https://github.com/FuelLabs/fuel-specs/blob/master/specs/protocol/abi.md#array

But now arrays in Sway are defined as `[T; size]` for type `T` and the generated ABI looks like `"type":"[T; size]"`. 

This broke the array support in the SDK and we should fix it by changing the parsing from `T[n]` to `[T; size]`. 

- [x] Change ABI parsing from `T[n]` to `[T; size]`;
- [x] Update all tests in harness to include the right json ABI;
- [x] Update the `fuel-specs`'s ABI section.

**Comment by QuinnLee** [comment]
👀

**Comment by digorithm** [comment]
> 👀

Was about to tag you and the TS folks haha. The same issue should exist in `fuels-ts`.
