### ISSUE TITLE
Fetch the default values for the transaction from the network instead of hardcoding

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuels-rs#1113]
Fetch the default values for the transaction from the network endpoint instead of hardcoding them in the code directly.

As an example, the current default value is more than allowed by beta 4, and it causes errors like:

```bash
>>> forc deploy --node-url http://beta-4.fuel.network/graphql --gas-price 1 
Error: Decode error: Custom { kind: Other, error: "Response errors; TransactionGasLimit" }
```

**Comment by hal3e** [comment]
This issue was done in: https://github.com/FuelLabs/fuels-rs/pull/1121.
