### ISSUE TITLE
Map Sway's `AssetId` to `fuel_types::AssetId` in `abigen!` bindings

### ISSUE THREAD

**Issue by segfault-magnet** [FuelLabs/fuels-rs#1134]
`AssetId` is no longer an alias in Sway. Update `abigen` to not generate custom `AssetId` structs but rather use `fuel_types::AssetId`.

**Comment by segfault-magnet** [comment]
[feat/asset_id_abigen](https://github.com/FuelLabs/fuels-rs/tree/feat/asset_id_abigen) @hal3e

**Comment by hal3e** [comment]
closed in: https://github.com/FuelLabs/fuels-rs/pull/1148
