### ISSUE TITLE
Revert ignoring testnet_hello_world test

### ISSUE THREAD

**Issue by Br1ght0ne** [FuelLabs/fuels-rs#1144]
Once https://github.com/FuelLabs/fuel-core/issues/1384 is in, https://github.com/FuelLabs/fuels-rs/pull/1143 should be reverted.

**Comment by digorithm** [comment]
This should be closed since #1143 went in, right?

**Comment by Br1ght0ne** [comment]
@digorithm Once the fuel-core issue is in, we can revert our PR (e.g. re-enable the test), and _then_ this issue will be closed. :)

**Comment by digorithm** [comment]
Sorry, what fuel-core issue?

**Comment by Br1ght0ne** [comment]
@digorithm https://github.com/FuelLabs/fuel-core/issues/1384
