### ISSUE TITLE
Use zeroized for zeroing out memory that housed secrets

### ISSUE THREAD

**Issue by segfault-magnet** [FuelLabs/fuels-rs#1157]
We should use the `zeroized` crate to wipe down all memory that used to contain secrets.

Off the top of my head, those places are:
1. The transaction builder and the keys stored there
2. Wallets

**Comment by gww-fuel** [comment]
This is part of broader security topic, everyone invited to improve on that:

* https://github.com/FuelLabs/security-guild/issues/6
