### ISSUE TITLE
Make `fuels-accounts` WASM compatible 

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuels-rs#1165]
### Background
- We're adding support for indexing predicates on the indexer
- Indexing predicates isn't enough, we also need to verify that predicates came from where they're supposed to come from
- I have read over the SDK predicate docs [here](https://docs.fuel.network/docs/fuels-rs/predicates/) and understand that using the predicate ABI, and a provider, one can do some predicate derivations

### Issue
- In order to verify that predicates are from the proper source @Voxelot has been kind enough to list detailed steps for doing so, that are indexer friendly
  - Those steps are [here](https://github.com/FuelLabs/fuel-indexer/issues/886)
    - Specifically [this](https://github.com/FuelLabs/fuel-indexer/issues/886#issuecomment-1756670213) comment
      - And specifically Section 3.2 within that ☝🏼 comment

### What do I ideally need?
- Ideally I need some way to derive the predicate root, at runtime, for an indexer, in a WASM-friendly way
  - The alternative is just using the non-WASM-friendly components (e.g., provider) and making FFI calls in/out of the indexer
    - Problem with this approach is that we'd effectively have to use a single provider for _all_ indexers and _all_ predicates
      - This might be fine?
- I do have access to:
  - The predicate ABI
  - The predicate bytecode
  - The predicate data/args
  - The relevant input/output coins
- I'm open on the best SDK way to do this however

cc @segfault-magnet @hal3e

**Comment by hal3e** [comment]
There is an associated function called `Predicate::calculate_address(code: &[u8], chain_id: u64)` that returns the predicate root/address given the predicate bytecode and chain_id. Is this enough for the use-case ?

**Comment by ra0x3** [comment]
@hal3e 
- I got a response from you on this via email, but I don't see the comment now 😅 
- Comment was:
> There is an associated function called Predicate::calculate_address(code: &[u8], chain_id: u64) that returns the predicate root/address given the predicate bytecode and chain_id. Is this enough for the use-case ?

- Yes, `calculate_address` is what I'll need to use
- `code` being the literal predicate byte code?
- @segfault-magnet previously mentioned that I'd have to make a network call to get the `chain_id`
  - Is this `chain_id` something that might change often for a given predicate?
    - I'm wondering if I can just grab this at compile time and then just bake it into the indexer module (again, this will only work if the `chain_id` never changes)

- My last question was, the comment I linked to above ☝🏼 (the indexer comment with Brandon's explanation) mentions "injecting the predicate args/configurables into the predicate template"
  - This "injected predicate" (predicate with config vars injected) is what I would pass to `calculate_address` (I believe)
  - This sounds like something that would have to be done at runtime, since I'd have to extract the predicate data from the transaction when the transaction comes in 
    - And if this has to be done at runtime, then I will need to call `MyPredicateEncoder::encode_data` and `Predicate::load_from` from the WASM module --- so these would have to be WASM-friendly
      - **Is the usage of `Predicate` in this way WASM friendly?**


Happy to hop on a call if that makes things easier, I know this is a lot :)

**Comment by ra0x3** [comment]
Spoke with @hal3e offline about this and I'll update this issue title to reflect the work he mentions needs to be done
