### ISSUE TITLE
Remove `[patch.crates-io]` from `Cargo.toml` once all crates are updated and released

### ISSUE THREAD

**Issue by hal3e** [FuelLabs/fuels-rs#1201]
`Cargo.toml` currently uses patched branches of several crates. Once the crates are updated to support `beta-5` and released we should remove them from `[patch.crates-io]`

**Comment by digorithm** [comment]
Note for ourselves: we should also remove 

```
[patch.'https://github.com/fuellabs/sway']
std = { git = "https://github.com/fuellabs/sway", branch = "feat/transaction-policies" }
```

From one of our `Forc.toml` files once that's merged.

**Comment by hal3e** [comment]
Closed with: https://github.com/FuelLabs/fuels-rs/pull/1214 and  https://github.com/FuelLabs/fuels-rs/pull/1225
