### ISSUE TITLE
cargo test with harness.rs taking unrealistically long time to finish

### ISSUE THREAD

**Issue by harshnambiar** [FuelLabs/fuels-rs#1242]
I am new to the Fuel Network and I am running a [simple smart contract](https://github.com/harshnambiar/hello_sway). It compiles just fine but as soon as it is time for cargo test, it gets stuck for quite a while (> 10 mins but not sure considering I left for a walk after that time but it was done by the time I got back (35 mins)). Is this normal? Is there another way to write the tests that won't take really long to execute?

Specifications:
fuelup 0.20.0
forc 0.46.1
cargo 1.74.1 (ecb9851af 2023-10-18)

**Comment by digorithm** [comment]
Hey there, I've just tested your code, and it finished in 28s: 

<img width="756" alt="image" src="https://github.com/FuelLabs/fuels-rs/assets/3484025/803aaaba-822f-4718-a3d5-be12c916457a">

Running with these deps:

```
active toolchain
-----------------
latest-aarch64-apple-darwin (default)
  forc : 0.46.1
    - forc-client
      - forc-deploy : 0.46.1
      - forc-run : 0.46.1
    - forc-doc : 0.46.1
    - forc-explore : 0.28.1
    - forc-fmt : 0.46.1
    - forc-index : 0.24.3
    - forc-lsp : 0.46.1
    - forc-tx : 0.46.1
    - forc-wallet : 0.3.0
  fuel-core : 0.20.5
  fuel-core-keygen : Error getting version string
  fuel-indexer : 0.24.3
```

So, it shouldn't be a version mismatch. Where does it get stuck/take too long for you? 

Also, as a side, these types of questions are better to ask on the forum: https://forum.fuel.network/. There, we have active community members reading and answering questions.

I'm closing this issue in the meantime but feel free to keep this discussion going.

**Comment by harshnambiar** [comment]
> Hey there, I've just tested your code, and it finished in 28s:
> 
> <img alt="image" width="756" src="https://private-user-images.githubusercontent.com/3484025/294260490-803aaaba-822f-4718-a3d5-be12c916457a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDY0ODUsIm5iZiI6MTcwNDcwNjE4NSwicGF0aCI6Ii8zNDg0MDI1LzI5NDI2MDQ5MC04MDNhYWFiYS04MjJmLTQ3MTgtYTNkNS1iZTEyYzkxNjQ1N2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMDkyOTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjI0YjVmODY5ZGVjZDg4MmE3YzA0MmYyM2VmMjYxYjA0OWMzMzgwM2JhZmI1OTRiZmE3NjJhMzI1NmQyY2JmNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DsDo-zJZMiMmw-lBiR7NCL3jC_-VhlgfOfa8K517Rlw">
> Running with these deps:
> 
> ```
> active toolchain
> -----------------
> latest-aarch64-apple-darwin (default)
>   forc : 0.46.1
>     - forc-client
>       - forc-deploy : 0.46.1
>       - forc-run : 0.46.1
>     - forc-doc : 0.46.1
>     - forc-explore : 0.28.1
>     - forc-fmt : 0.46.1
>     - forc-index : 0.24.3
>     - forc-lsp : 0.46.1
>     - forc-tx : 0.46.1
>     - forc-wallet : 0.3.0
>   fuel-core : 0.20.5
>   fuel-core-keygen : Error getting version string
>   fuel-indexer : 0.24.3
> ```
> 
> So, it shouldn't be a version mismatch. Where does it get stuck/take too long for you?
> 
> Also, as a side, these types of questions are better to ask on the forum: https://forum.fuel.network/. There, we have active community members reading and answering questions.
> 
> I'm closing this issue in the meantime but feel free to keep this discussion going.

I think it's probably an architecture problem and not one of version. I'm on i5 Intel core maybe that's why. Also, the forum hasn't been super helpful as of now, and it's just one dude who does his best to help. But I understand this issue should be closed as we can't do anything about it.
