### ISSUE TITLE
Encoder/decoder revamp 

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/fuels-rs#1246]
The Sway compiler is going through a long-discussed revamp of its encoder/decoder scheme, eventually leading to an intermediary representation that both the SDK and the compiler will target.

Tasks:

1. https://github.com/FuelLabs/sway/pull/5306
2. https://github.com/FuelLabs/fuels-rs/pull/1259
2. https://github.com/FuelLabs/sway/issues/4769
3. https://github.com/FuelLabs/fuels-rs/pull/1249
4. https://github.com/FuelLabs/fuels-rs/issues/1278
5. https://github.com/FuelLabs/fuels-rs/issues/1279

This will enable, once and for all, the support of nested heap types, solving many open issues related to this problem, such as:

1. https://github.com/FuelLabs/fuels-rs/issues/1151
2. https://github.com/FuelLabs/fuels-rs/issues/1152
3. https://github.com/FuelLabs/fuels-rs/issues/1158
4. https://github.com/FuelLabs/fuels-rs/issues/1046
5. https://github.com/FuelLabs/fuels-rs/issues/901
6. https://github.com/FuelLabs/fuels-rs/issues/898
7. https://github.com/FuelLabs/fuels-rs/issues/866

As seen above, many issues stem from a lack of support for nested heap types. This new encoding/decoding scheme implemented inside the Sway compiler will enable this.

**Comment by hal3e** [comment]
We have several issues here that were solved with the `experimental` log encoding PR. Should we close them or keep them until we have this stabilized ?

**Comment by digorithm** [comment]
@hal3e That's true. I'll check which ones of those were resolved and close them.

**Comment by digorithm** [comment]
Closing this as most of the work has been done, and the leftovers will be pushed as a follow-up work.
