### ISSUE TITLE
Support new encoder/decoder for scripts and predicates

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/fuels-rs#1279]
Part of https://github.com/FuelLabs/fuels-rs/issues/1246.

Blocked by: 

- https://github.com/FuelLabs/sway/issues/5513

**Comment by Matttioboy** [comment]
epic work

**Comment by hrrl** [comment]
good

**Comment by digorithm** [comment]
Closing this because it's been mostly done. String slices and `RawSlice` support for scripts will be added later.
