### ISSUE TITLE
Cannot load keystore file which `forc-wallet new` generated

### ISSUE THREAD

**Issue by mtroym** [FuelLabs/fuels-rs#1289]
I used forc-wallet to generate new wallet under my project dir `"project_root/.wallets/wallet_fuel.json"` and encrypt with empty passphrase.

my wallet gen script:
 
```bash
mkdir -p .wallets

wallet_name=fuel
if [[ -n $1 ]]; then
  wallet_name=$1
fi

forc wallet --path=./.wallets/wallet_"$wallet_name".json new --force
```

and triple "Enter"s to get an encryped keystore json file under `"project_root/.wallets/wallet_fuel.json"`

Then I use Rust SDK to restore my wallet:

```Rust
fn restore_wallets(password: &str, some_provider: Option<Provider>) -> Result<WalletUnlocked> {
    let dir = std::env::current_dir()?;
    let provider: Provider = some_provider.unwrap();
    let path = dir.join(".wallets/wallet_fuel_test.json");
    info!("The wallet info stored at {}", path.display());
    let _recovered_wallet = WalletUnlocked::load_keystore(
        path, password, Some(provider.clone()))?;
    Ok(_recovered_wallet)
}
```

The function panicked, and results in 

`Decrypted key should have a correct size: InvalidSecretKey`

**Comment by mtroym** [comment]
I provide my wallet gen script:
 
```
mkdir -p .wallets

wallet_name=fuel
if [[ -n $1 ]]; then
  wallet_name=$1
fi

forc wallet --path=./.wallets/wallet_"$wallet_name".json new --force
```

and triple "Enter"s to get an encryped keystore json file under `"project_root/.wallets/wallet_fuel.json"`

**Comment by MujkicA** [comment]
Thanks for bringing this to our attention!

The issue seems to be the`forc-wallet` generating keys of variable length instead of 32 bytes. 

I'll close this on the SDK side and you can refer to https://github.com/FuelLabs/forc-wallet/issues/165 for further tracking of this issue.

**Comment by mtroym** [comment]
@MujkicA Thanks, I wanna contribute as well, any option could I reach out team?
