### ISSUE TITLE
Read testnet wallets' private keys from environment variables

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/fuels-rs#1297]
To avoid leaking testnet wallets' private keys, we shouldn't hardcode these wallets' private keys like we do, e.g., in here:

https://github.com/FuelLabs/fuels-rs/blob/master/packages/fuels/tests/providers.rs#L597

Instead, we should read these private keys from environment variables and set them in the GitHub CI environment. Similar to what was done recently on the TS SDK: https://github.com/FuelLabs/fuels-ts/pull/1858. We should generate a new test wallet, fund it through the faucet, and then set the env var on GitHub.

**Comment by arboleya** [comment]
Maybe not relevant here, but as we also had references to [`WALLET_ADDRESS`](https://github.com/FuelLabs/fuels-ts/blob/master/packages/fuel-gauge/src/e2e-script.test.ts#L116), we started reading it from the environment/secrets as well. If we need to change things in the future, no code modifications will be necessary.

**Comment by digorithm** [comment]
> Maybe not relevant here, but as we also had references to [`WALLET_ADDRESS`](https://github.com/FuelLabs/fuels-ts/blob/master/packages/fuel-gauge/src/e2e-script.test.ts#L116), we started reading it from the environment/secrets as well. If we need to change things in the future, no code modifications will be necessary.

💯 we should do the same here.

**Comment by Br1ght0ne** [comment]
Should be fixed (env vars will be used) in #1471.
