### ISSUE TITLE
Remove workaround placed to handle temporary mandatory arguments

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/fuels-rs#13]
As discussed in https://github.com/FuelLabs/fuels-rs/pull/11#discussion_r758243462, once the Sway compiler removes the need to have gas, color, and coin amount as mandatory arguments to every ABI method, we should go back to this place in the `fuels-rs` code and remove the workaround.

**Comment by adlerjohn** [comment]
We can tackle this after https://github.com/FuelLabs/sway/pull/859 lands and a new release of the compiler is cut

**Comment by adlerjohn** [comment]
https://github.com/FuelLabs/sway/pull/859 has been merged, so we only need a new release of the compiler.

**Comment by vnepveu** [comment]
Compiler was updated to 0.6 with https://github.com/FuelLabs/sway/commit/35e5a2f12e137953b82470e9637e4969ca064e4a
