### ISSUE TITLE
Integrate wallet/signer abstraction with the contract abstraction

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/fuels-rs#130]
Now that we have a basic wallet and signer interface to sign transactions, it needs to be integrated with the contract abstraction in `fuels-rs`. Currently, all transactions sent by a contract instance are unsigned -- they work because the client isn't checking for signatures, but eventually, it will.

Contract instantiation, then, needs to take in a signer, and have it accessible through the contract interface (and also use the signer to sign the transaction before sending it).

The implementation and API design and details are still up for discussion, though.

**Comment by digorithm** [comment]
Note: A step in this direction was done in the TS SDK: https://github.com/FuelLabs/fuels-ts/pull/182.

**Comment by vnepveu** [comment]
PR #154 was a step towards this. Work on signer still needs to be done though.
