### ISSUE TITLE
`adjust_for_fee` does not filter already used inputs

### ISSUE THREAD

**Issue by hal3e** [FuelLabs/fuels-rs#1314]
While working on https://github.com/FuelLabs/fuels-rs/pull/1313 I found a bug in the `adjust_for_fee` method. When adjusting the fee, we do not take into consideration coins/messages that were already added to the `TransactionBuilder`. After calculating the missing base amount, we just request the amount from the provider and we can get back a coin that is already in our inputs leading to duplicate utxos. Minimal test rerpo:

```rust
#[tokio::test]
async fn test_transfer2() -> Result<()> {
    let mut wallet_1 = WalletUnlocked::new_random(None);

    let base_asset_id = AssetId::default();
    let coins = setup_single_asset_coins(wallet_1.address(), base_asset_id, 1, 3);

    let provider = setup_test_provider(coins, vec![], None, None).await?;

    wallet_1.set_provider(provider);

    wallet_1
        .transfer(
            &Bech32Address::default(),
            3,
            AssetId::default(),
            TxPolicies::default().with_tip(1),
        )
        .await?;

    Ok(())
}
```

**Comment by MujkicA** [comment]
@segfault-magnet taking this off your hands because it relates to #1361
