### ISSUE TITLE
`404` error from `Provider::connect("beta-5.fuel.network")` on version `0.56.0`

### ISSUE THREAD

**Issue by K1-R1** [FuelLabs/fuels-rs#1315]
The code below, from the [connecting docs](https://docs.fuel.network/docs/fuels-rs/connecting/external-node/), produces:
```
called `Result::unwrap()` on an `Err` value: Provider("Server returned 404 Not Found: ")
```
on `0.56`. It works correctly on the previous version `0.55`.

```rust
use fuels::{crypto::SecretKey, prelude::*};
use std::str::FromStr;

#[tokio::main]
async fn main() {
    // Create a provider pointing to the testnet.
    let provider = Provider::connect("beta-5.fuel.network").await.unwrap();

    // Setup a private key
    let secret =
        SecretKey::from_str("a1447cd75accc6b71a976fd3401a1f6ce318d27ba660b0315ee6ac347bf39568")
            .unwrap();

    // Create the wallet
    let wallet = WalletUnlocked::new_from_private_key(secret, Some(provider));

    // Get the wallet address. Used later with the faucet
    dbg!(wallet.address().to_string());
}

```

**Comment by Voxelot** [comment]
This might be due to a change in the graphql path: https://github.com/FuelLabs/fuel-core/pull/1725

How is this not caught in integration tests?

**Comment by hal3e** [comment]
> This might be due to a change in the graphql path: [FuelLabs/fuel-core#1725](https://github.com/FuelLabs/fuel-core/pull/1725)
> 
> How is this not caught in rust-sdk integration tests?

`fuels-rs: 0.56.0` is using `fuel-core: 0.23.0` so it is not compatible with `beta-5` which uses `fuel-core: 0.22.4`

**Comment by digorithm** [comment]
This seems to be a version incompatibility. The version checker didn't catch it because this is a breaking change in the gql path itself, so we cannot get information about what version of the core is running on the URL. Closing it for now.
