### ISSUE TITLE
Get full balance from wallet

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/fuels-rs#132]
Currently, we have the method `get_coins()`, but it returns a relatively hard to read `Vec<Coin>`, not sorted by status and color/asset_id. 

Ideally, especially when integrating with wallet apps, the user would like to read something like:
```
coin 1: 100
coin 2: 200
```

Where the amount of a certain coin is a UTXO that's _not_ spent (`get_coins()` will return coins with any status) and the coin color (now called asset ID) aggregates the unspent UTXOs for that asset ID, so that's possible to generate something like the example above, i.e. `asset_id: <amount>` for each asset_id owned by that wallet address.

**Comment by vnepveu** [comment]
Closing in favor of #266
