### ISSUE TITLE
Memory-write-overlap bug

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/fuels-rs#1469]
### Context

Old code base used `forc 0.49.X` with `fuels 0.55.0` in which tests have passed.

Repo was bumped to `forc 0.61.2` and `fuels 0.64.0` and some tests started to fail because different values were reported.

In this particular issue it's a new revert error which was not happening before. Moreover, the SDK was bumped again to `0.65.1` and the revert persists.

### Repro

1. Clone https://github.com/Braqzen/memory-write-overlap-bug
2. In the repo `forc build`
3. Then `cargo test`

### Test Error

![1](https://github.com/user-attachments/assets/573abab3-f31d-4fc2-be46-0ccd8eb9fe06)

**Comment by hal3e** [comment]
@Braqzen thank you for the bug report and for the nice repro. This is a compiler bug and I will forward it to the compiler team. I will leave this issue open until we confirm the bug is fixed.

**Comment by hal3e** [comment]
@Braqzen It was confirmed that this is a compiler bug. We have created a new issue on the sway repo: https://github.com/FuelLabs/sway/issues/6361
