### ISSUE TITLE
Blob tx / large contract support

### ISSUE THREAD

**Issue by segfault-magnet** [FuelLabs/fuels-rs#1470]
Adapt the SDK to support blob transactions and deploying contracts using them.

Core side: https://github.com/FuelLabs/fuel-specs/issues/589

[A nice diagram](https://github.com/FuelLabs/fuels-ts/issues/2741) by @arboleya

**Comment by arboleya** [comment]
I believe the diagram comes from @JoshuaBatty. 😅
