### ISSUE TITLE
Unrecognized custom type aliases

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/fuels-rs#1479]
In Sway you may define a `type` as another type ex. `type ABC = u64;`.

The Rust SDK has no issue coercing types into the base type, in this case the `u64`, so as long as you use the `u64` in all places that define the `ABC` type then everything works.
The issue is more of an inconvenience, which is unexpected, which is you cannot use `ABC` itself because it is not recognized as a type in the SDK.

It would be nice if the SDK exposed custom type aliases.

Steps to repro:

1. clone https://github.com/Braqzen/type-alias-bug
2. `forc build`
3. `cargo test`

**Comment by segfault-magnet** [comment]
Ty for the practical repro :) 

Unfortunately the compiler doesn't export the aliases into the generated ABI (this shows up as `u64` in the ABI), so there is no way for the sdk to generate them. 

Closing as not related to the sdk. Will ping the compiler team but they're probably aware of it.
