### ISSUE TITLE
Bump `forc` to `0.6`

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/fuels-rs#148]
Probably requires #13 to be done simultaneously.

**Comment by mitchmindtree** [comment]
Also requires https://github.com/FuelLabs/sway/pull/917 (along with a follow-up forc `0.6.1` release) for the tests to pass as witnessed by @vnepveu (see [here](https://github.com/FuelLabs/sway/issues/915)).

**Comment by vnepveu** [comment]
After trying to update `forc` to `0.6`, it seems some tests are broken for no reason: 
```
---- abigen_different_structs_same_arg_name stdout ----
  Bytecode size is 156 bytes.
Contract deployed @ 9906afc4d317e5d16ff3694bd14c0f908f1a5c21a685f6e778e18b2b363d73da
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `43`', fuels-abigen-macro/tests/harness.rs:1337:5
```. If you look a the concerned contract, there is *afaik* no reason its behavior should be changed by the `forc` update.

**Comment by digorithm** [comment]
@vnepveu https://github.com/FuelLabs/fuels-rs/blob/master/fuels-core/src/code_gen/functions_gen.rs#L117-L135 

We're still checking for the 3 mandatory arguments `(u62, u62, b256)` and encoding it in the call. `forc`/`sway` `0.6.x` removed it, so if you compile it with `forc` `0.6.x`, it will be deployed with all methods _not_ including these args in the function signature but the SDK will still be encoding it, leading to all sorts of errors. 

I'm currently working on these changes to support `forc` `0.6` though.
