### ISSUE TITLE
Error in launching E2E tests

### ISSUE THREAD

**Issue by AurelienFT** [FuelLabs/fuels-rs#1492]
I tried to build the tests with the command on the README :
```
 forc build --release --path e2e
```

I have this error : 
```
   Compiling library core (/Users/aurelienfoucault/.forc/git/checkouts/std-9be0d6062747ea7/5e3055ff2513804ea65115d99ae54e28a82555f2/sway-lib-core)
error
 --> /Users/aurelienfoucault/.forc/git/checkouts/std-9be0d6062747ea7/5e3055ff2513804ea65115d99ae54e28a82555f2/sway-lib-core/src/slice.sw:5:6
  |
3 | 
4 | 
5 | impl<T> &__slice[T] {
  |      ^ The generic type parameter "T" is unconstrained.
6 |     pub fn ptr(self) -> raw_ptr {
7 |         let (ptr, _) = asm(s: self) {
  |
____

  Aborting due to 1 error.
error: Failed to compile core
```

My versions : 

- Rust : 1.79.0
- Forc : 0.62.0
- Fuelup : 0.26.0

Maybe this issue isn't related to this repository, in this case I will be happy to move it whenever you want :)

**Comment by hal3e** [comment]
This is in general a `sway` issue as the error originates in the sway's core library; however,
we have not encountered this error while we were using `forc 0.62.0`. We are currently using `forc 0.63.1` on the master branch. Could you try updating `forc` and building again ?

**Comment by AurelienFT** [comment]
It fixed the issue. Thank you !
