### ISSUE TITLE
Consider moving receipt parsing and ABI decoding logic to its own crate

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/fuels-rs#152]
The details are still being worked on, this issue is, initially, just to track the idea. 

The motivation is that, eventually, `sway` will need to use the receipt parsing logic that currently lives in here in `fuels-rs`, this would introduce a circular dependency between `sway` and `fuels-rs`. Not good. 

The solution would be to have another repo/crate (`fuel-receipts`, name to be defined) where the receipt parsing logic and the ABI decoding logic from `fuels-rs` would be moved there. `fuels-rs` and `sway` would both depend on it. 

In addition to that, `JsonABI` from `sway` (https://github.com/FuelLabs/sway/blob/master/sway-types/src/lib.rs#L345-L364) could also be moved upstream, because that's not something specific to `sway`, but specific to the FuelVM ABI specification that the Sway compiler conforms to.

**Comment by digorithm** [comment]
cc @adlerjohn @mitchmindtree

**Comment by adlerjohn** [comment]
An alternative to this would be to actually keep everything in `fuels-rs` that isn't Sway-specific and move the Sway-specific things (back) into `sway`.

**Comment by mitchmindtree** [comment]
Yeah it might be worth untangling the `sway` dependencies from `fuels-rs` first - I think doing so might reveal it's totally fine to have the receipt parsing stuff along with the rest of the SDK.
