### ISSUE TITLE
Call and send to contract

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/fuels-rs#153]
There should be a distinction between calling a contract, which dry runs essentially, and sending to a contract, which actually sends a valid tx to be included on-chain. The former can be used for e.g. view or pure functions,and does not require the tx to be unique since it's never included on-chain. The latter can be used for stateful writes, and requires the tx to be unique in some way.

Names subject to change, not sure if "call" and "send" are the best names, but IIRC this is what ethers uses.

If a notion of state mutability is added to the ABI, then the SDK could actually warn if you attempt to call a method that mutates the state.

**Comment by digorithm** [comment]
We discussed this previous here https://github.com/FuelLabs/fuels-rs/issues/90 (and the issue linked in it). IIRC, the summary of that discussion was that we either:

1. Let the user decide whether to use `call()` or `send()`;
2. Have the compiler output, in the ABI, the state mutability of each method.

(2) is the best but it seems like a major effort in the compiler. Maybe we could start with (1) for now and then, once the compiler implements that, we can do (2)?

**Comment by adlerjohn** [comment]
(2) is not sufficient because sometimes the user will want to dry-run a tx without persistently modifying state.

**Comment by digorithm** [comment]
That's true. So I guess in the end it'll be a mix of both. And (2) will help the SDK detect bad cases (calling `.call()` on a method that mutates state as you mentioned).
