### ISSUE TITLE
The sdk needs to support variable outputs.

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/fuels-rs#171]
Ref: slack thread: https://fuellabs.slack.com/archives/C02CX4JVCSJ/p1647526324734319?thread_ts=1647464981.548979&cid=C02CX4JVCSJ

**Comment by adlerjohn** [comment]
This can be accomplished by something like `.append_variable_outputs(num: u64)` in the tx builder which appends `num` variable outputs to the tx.
