### ISSUE TITLE
Remove `pub` from constant `DEFAULT_INITIAL_BALANCE`

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-rs#180]
This was discussed here: https://github.com/FuelLabs/fuels-rs/pull/175#discussion_r835701407

Trying to make it `pub(crate)` would also require changes on `fuels-signers/src/util.rs`.

**Comment by vnepveu** [comment]
So after some testing I dont _think_ we can just remove the `pub` keyword unless there is some Rust feature I missed that allows a `constant` during tests. Otherwise, we either move the constant to the relevant modules, or we keep the `pub` keyword.

**Comment by adlerjohn** [comment]
How about `pub(crate)`?

**Comment by vnepveu** [comment]
`pub(crate)` isn't good because the tests using the constant is used both in `harness.rs` (crate `fuels-abigen-macro`) and `fuels-signers` (for the utils functions for the providers). The `utils` could be reorganized IMO but it's outside the scope of this issue.
