### ISSUE TITLE
Expose script length publicly

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/fuels-rs#181]
For testing that the `scriptLength` field of txs is set correctly, downstream crates need to know the length of the script used to call ABI methods. This should be exposed publicly.

Also script data length.

**Comment by vnepveu** [comment]
If I'm not mistaken this is an upstream issue in `fuel-tx` for updating the `Transaction` type: https://github.com/FuelLabs/fuel-tx/blob/3ad3936c36401cf36c0e80352039294becc9cc94/src/transaction.rs#L68

**Comment by adlerjohn** [comment]
Oh that's actually a good point! The transaction can just be used.
