### ISSUE TITLE
Actually forward gas on call

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/fuels-rs#184]
Actually forward the amount of gas on contract calls

**Comment by m3talsmith** [comment]
@digorithm I'm happy to take this one on.

**Comment by digorithm** [comment]
Awesome, go for it!

**Comment by adlerjohn** [comment]
This issue is to forward an amount of gas with a call, not all remaining gas (which is the current behavior). To do this, you need to load the amount of gas into a register.
