### ISSUE TITLE
feat: SDK should offer an option to see the transaction before using `call` or `simulate` on it

### ISSUE THREAD

**Issue by vnepveu** [FuelLabs/fuels-rs#200]
*  We should build  a new struct that gets returned with a `.build()`, which includes the tx and also a method `.call()` which does the call on the tx that's already built.

**Comment by digorithm** [comment]
Doesn't this already exist? Isn't that what `method_hash` and the struct `ContractCall` is for? https://github.com/FuelLabs/fuels-rs/blob/856e311891678e8e2efa944ad0d37fc90a88aee2/packages/fuels-contract/src/contract.rs#L304-L338

Here's an example:

```Rust
// Notice how we're not appending `.call()` to it. 
let contract_call = contract_instance.increment_counter(5);
dbg!(&contract_call);
```

Output:

```
[packages/fuels-abigen-macro/tests/harness.rs:671] &t = ContractCall {
    fuel_client: FuelClient {
        url: Url {
            scheme: "http",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: Some(
                Ipv4(
                    127.0.0.1,
                ),
            ),
            port: Some(
                54762,
            ),
            path: "/graphql",
            query: None,
            fragment: None,
        },
    },
    encoded_args: [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        5,
    ],
    encoded_selector: [
        0,
        0,
        0,
        0,
        250,
        249,
        13,
        211,
    ],
    contract_id: 0xb9acf23801d63ea7cc9169a052339c5b916fffa815cbe76dbcbe0148ad46143c,
    tx_parameters: TxParameters {
        gas_price: 0,
        gas_limit: 1000000,
        byte_price: 0,
    },
    call_parameters: CallParameters {
        amount: 0,
        asset_id: 0x0000000000000000000000000000000000000000000000000000000000000000,
    },
    maturity: 0,
    datatype: PhantomData,
    output_params: [
        U64,
    ],
    compute_calldata_offset: false,
    wallet: Wallet {
        address: 0x45ac9639695236a273fe37733ef9df09220451ddd6b805c98b518e2783167e37,
    },
    variable_outputs: None,
    external_contracts: None,
}
```

Then, appending `.call()` to this `ContractCall`... calls it.

**Comment by adlerjohn** [comment]
That doesn't really let me know what the script is, or the script length. Ref: https://github.com/FuelLabs/fuels-rs/issues/181

**Comment by digorithm** [comment]
Right. Then maybe extend `ContractCall` to include all this missing information? Calling a method that was generated by the `abigen!` is already a builder pattern (doesn't actually make the call) that carries the transaction information (that currently doesn't expose it all), and that can be executed by attaching `call()` to it (what's being proposed by the issue).

**Comment by adlerjohn** [comment]
Instead of duplicating all the tx for things that are _generated_ rather than _set_ (e.g. script length isn't set, it's generated), my proposal is to have a struct that simply wraps a tx with an additional `.call()` method.

As follows:

1. A new struct `BuiltTx` (name subject to change), which includes a `fuel_tx` transaction, and a method `.call()` that does the call (but not tx construction logic) of the current `ContractCall.call()`.
1. Add a new method `ContractCall.build()` that does the tx building logic of the current `ContractCall.call()`, and returns a `BuiltTx`.
1. Refactor `ContractCall.call()` to simply be `.build().call()`.

**Comment by vnepveu** [comment]
Not a big fan of having to chain  `.build().call()` everytime, IMO the building should be abstracted away by default but accessible if desired

**Comment by digorithm** [comment]
From a usability perspective, having to chain too many methods to perform basic tasks (.a().b().c()...) isn't too nice. Scala devs can certainly confirm that (me included). It gets messy real quick, plus major cognitive overhead to achieve simple things. 

We already have a non-negligible number of methods that you have to chain if you're configuring tons of things, including adding external contracts. 


But then again, this is just my opinion.

**Comment by adlerjohn** [comment]
Ah I wasn't clear about my proposal.

For 3 my proposal _wasn't_ to remove `.call()` from `ContractCall`. It was to refactor _the implementation_ of `.call()` to simply use `.build().call()` under the hood.
