### ISSUE TITLE
Update SDK for Sway's change to use IR by default.

### ISSUE THREAD

**Issue by otrho** [FuelLabs/fuels-rs#201]
Sway is switching to use IR by default here: https://github.com/FuelLabs/sway/pull/1130

Contract calls are slightly different compared to current Sway -- user args are always wrapped in a struct, even if there is only one.  This is a bit more consistent and disregards the need for special casing.

Also, values are returned from a contract call via `RET` or `RETD` based now on the value type, not size.  `unit`, `bool`, `byte` and `u64` are 'copy' types returned via `RET`, otherwise `RETD` is used.

**Comment by digorithm** [comment]
Note: this is momentarily blocked by https://github.com/FuelLabs/sway/issues/1146.

**Comment by mohammadfawaz** [comment]
`forc v0.10.0` is now [available](https://github.com/FuelLabs/sway/releases/tag/v0.10.0).

**Comment by otrho** [comment]
I think the design we want is to actually keep the special casing for small struct args but use the newer 'by-type` conventions for `RET` vs `RETD` as mentioned in the description.
