### ISSUE TITLE
Add a CLI flag to enable "simulate-only" mode

### ISSUE THREAD

**Issue by iqdecay** [FuelLabs/fuels-rs#208]
- If that flag is enabled, each transaction would have a `simulate` field set to `true`

**Comment by Salka1988** [comment]
Don't we already have this? `call()` || `simulate()`

**Comment by iqdecay** [comment]
Closing because we can already use `call` or `simulate` on a transaction. Trying to force all transactions to use `simulate` would create unnecessary complications.
