### ISSUE TITLE
Compile Sway contracts using latest (or at least version-pinned) `forc` in each CI run

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/fuels-rs#210]
# Problem

Currently, we commit the JSON ABI and compiled binary for each Sway test project, used in our test suite, all compiled manually. This leads to a big problem: these compiled binaries aren't frequently updated. This means updates in the compiler might break the SDK but not get caught in the CI pipeline, because the CI is running our test suite that's running test against currently existing Sway binaries, which was compiled at an earlier point in time, potentially using an earlier version of `forc`. 

# Solution

We must add the Sway compilation process in the CI pipeline, somehow. That means we would stop committing the compiled binaries and JSON ABI files, and these would be generated by, sway, a simple bash script that would install the latest `forc` (or a pinned version), run `forc build` for each test project, and then the test suite would run against these freshly compiled binaries.

**Comment by adlerjohn** [comment]
This may help (though I would prefer a Rust version): https://github.com/FuelLabs/sway/issues/1082

**Comment by digorithm** [comment]
I have a working version of this, but currently blocked by https://github.com/FuelLabs/sway/issues/1335 because building one of the test projects fails with the error mentioned in that issue.
