### ISSUE TITLE
Include salt gen process for ergonomics

### ISSUE THREAD

**Issue by SilentCicero** [FuelLabs/fuels-rs#215]
Currently, we force a developer to provide their own Salt and they have to bring their own library to do this. 

But in the vein and philosophy of Ethers.js (as Richard would put it), we want to make this an all-in-one stop shop for a developer to use Fuel. Including rand in the library and just having Salt pre-gen for now is much nicer than having to specify and include this every time. Just include it for ergonomics.

I'd like to see `rand` just included as a dependency for fuels-rs. I don't like specifying rand every-time. I think the general philosophy should be, if I have to do it everytime, then it should just be provided nicely as a default in the repo (even if its extra bulk).

This:
```rust
use fuel_tx::Salt;
use fuels_abigen_macro::abigen;
use fuels_contract::contract::Contract;
use rand::rngs::StdRng;
use rand::{Rng, SeedableRng};

// Generate Rust bindings from our contract JSON ABI
abigen!(MyContract, "./my-contract-abi.json");

#[tokio::test]
async fn harness() {
    let rng = &mut StdRng::seed_from_u64(2322u64);

    // Build the contract
    let salt: [u8; 32] = rng.gen();
    let salt = Salt::from(salt);

    let compiled = Contract::compile_sway_contract("./", salt).unwrap();
    let client = Provider::launch(Config::local_node()).await.unwrap();
    let contract_id = Contract::deploy(&compiled, &client).await.unwrap();
    println!("Contract deployed @ {:x}", contract_id);
```

Should be:
```rust
use fuels_abigen_macro::abigen;
use fuels_contract::contract::Contract;

// Generate Rust bindings from our contract JSON ABI
abigen!(MyContract, "./my-contract-abi.json");

#[tokio::test]
async fn harness() {
    let compiled = Contract::compile_sway_contract("./").unwrap();
    let client = Provider::launch(Config::local_node()).await.unwrap();
    let contract_id = Contract::deploy(&compiled, &client).await.unwrap();
    println!("Contract deployed @ {:x}", contract_id);
```

And if I want to see what the Salt that was generated, there should just be a trait or property of some kind to have visibility into it from the compiler or contract_id property.

My two cents.

**Comment by digorithm** [comment]
Oh, 100%. This is a great idea and the current way we ask the users to do their own rng was supposed to be just something temporary that was introduced at the very early stages of the SDK development. 

We just need to find some space in our sprints to tackle this one, but I'd say it should be a relatively high priority one because it would such a major QoL improvement.

**Comment by SilentCicero** [comment]
Further, deploying contracts could be reduced a lot by virtue of handy trait design:

```rust
use fuels_abigen_macro::abigen;
use fuels_contract::contract::Contract;

// Generate Rust bindings from our contract JSON ABI
abigen!(MyContract, "./my-contract-abi.json");

#[tokio::test]
async fn harness() {
    let compiled = Contract::compile_sway_contract("./", salt).unwrap();
    let client = Provider::launch(Config::local_node()).await.unwrap();
    let contract_id = Contract::deploy(&compiled, &client).await.unwrap();
    println!("Contract deployed @ {:x}", contract_id);

    let contract_instance = MyContract::new(contract_id.to_string(), client);
```

To something like:

```rust
use fuels_abigen_macro::abigen;
use fuels_contract::contract::Contract;

// Generate Rust bindings from our contract JSON ABI
abigen!(MyContract, "./my-contract-abi.json");

#[tokio::test]
async fn harness() {
    let client = Provider::launch(Config::local_node()).await.unwrap();
    let contract_instance = Contract::compile_and_deploy(MyContract, "./", &client).await.unwrap();
    
    println!("Contract deployed @ {:x}", contract_instance.contract_id);
```

**Comment by digorithm** [comment]
Wait... we don't compile within the SDK no more, we only load pre-compiled binaries, e.g.:

```rust
let compiled = Contract::load_sway_contract(path,salt).unwrap();
let id = Contract::deploy(&compiled, &provider, &wallet, TxParameters::default())
        .await
        .unwrap();
```

`compile_sway_contract()` has been deprecated and removed! 

Now, building on your (slightly outdated) suggestion, we could bundle load and deploy into `load_and_deploy()`. Or maybe `deploy()` could implicitly load?

**Comment by SilentCicero** [comment]
@digorithm given the above, then I need to also make an issue to update the Forc readme!

But yeah. Bundling and returning the contract instance is always preferred. It's more useful than just the contract_id.

**Comment by adlerjohn** [comment]
We have to be a little careful here: there's not really any reason to use a random salt instead of just 0, unless they're trying to deploy another contract with the same bytecode and initial storage, at which point they could always use 1, or 2. There's an argument to be made that you should keep the current method that accepts a salt, but also provide a method that simply uses 0 and doesn't require the user to provide a salt. Then if deploying fails with contract already exists, it can warn that the user needs to use the salt as follows.

This avoids the need for users to use `rand` at all in most cases.
