### ISSUE TITLE
Forc readme is out of date and needs to be updated

### ISSUE THREAD

**Issue by SilentCicero** [FuelLabs/fuels-rs#216]
The notation for compiling and deployment is out of date for the Forc readme:
https://crates.io/crates/forc

I.e. per Rodrigo in this issue comment:
https://github.com/FuelLabs/fuels-rs/issues/215#issuecomment-1101628302

We need to always keep the Readme up to date with the latest way to do things, and or point to a book that does.

**Comment by adlerjohn** [comment]
Closed by https://github.com/FuelLabs/sway/pull/1300

**Comment by binggh** [comment]
actually the text still needs to be updated to change `compile_sway_contract()` to `load_sway_contract()` instead - will open a separate PR

**Comment by adlerjohn** [comment]
Makes sense.
