### ISSUE TITLE
Potentially inaccurate comment

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/fuels-rs#220]
Looking here: https://github.com/FuelLabs/fuels-rs/blob/7fda121547ee28de91145f8e8034db7e02b79b48/packages/fuels-contract/src/contract.rs#L559
Tuples seem to be supported now: https://github.com/FuelLabs/fuels-rs/pull/205

Is there any logic in this function that needs to be changed? Or should the comment simply be removed?

**Comment by digorithm** [comment]
Resolved by latest developments.
