### ISSUE TITLE
Consider publishing `fuels-rs` crate as `fuels`?

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/fuels-rs#225]
I think the `.rs` is implied in that it's a Rust crate. This is quite a common convention for `-rs` repositories/projects, where the crate is a "Rust implementation" or "Rust API" for some tool that might have support for multiple languages.

**Comment by adlerjohn** [comment]
Not a bad idea.

https://github.com/gakonst/ethers-rs/blob/77bd9d49c88ca8bdced37f7554919e3c3d584310/Cargo.toml#L2
