### ISSUE TITLE
feat: support "empty" enums

### ISSUE THREAD

**Issue by vnepveu** [FuelLabs/fuels-rs#231]
Currently, "empty" enums such as 
```
enum SmallEnum {
    v1: (),
    v2: (),
}
```
are not correctly parsed by the SDK, because the `()` type is parsed as a custom type but has no component: 
```
 help: message: called `Result::unwrap()` on an `Err` value: MissingData("cannot parse custom type with no components")
```

**Comment by digorithm** [comment]
Is it a `bug` or is it a `feat: `? Title says feat, label says bug 😂
