### ISSUE TITLE
Readme.md doesn't include instructions on how to build and test the repo

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuels-rs#252]
As a new contributor to fuels-rs, the readme should include instructions on how to locally build and run all the tests. Currently, the only steps I could find were buried in the ci.yaml.

The only exception to this documentation is if testing is as simple as running `cargo test`. However, this repo requires a lot of setup to download forc and build all the pre-reqs before tests can run.

**Comment by Voxelot** [comment]
If it's possible to build the projects using forc as a library as a build/setup step for the e2e tests, that seems like the most developer/ergonomic solution as it would allow developers to only need the standard cargo commands.

**Comment by digorithm** [comment]
> If it's possible to build the projects using forc as a library during the build.rs/setup step for the e2e tests, that seems like the most developer/ergonomic solution as it would allow developers to only need the standard cargo commands.

While I agree it would be the most ergonomic solution, IIRC didn't we have that but then removed because of a cyclic dependency issue?

**Comment by Voxelot** [comment]
Currently, forc is a part of the sway repo, so yeah it seems like this could cause some circular issues with the test harness: https://github.com/FuelLabs/sway/blob/master/test/src/sdk-harness/Cargo.toml

**Comment by segfault-magnet** [comment]
If we make the forc lib a dev dependency of fuels-rs then we won't have a circle since dev dependencies are not acquired by sway when it states its dependency on 'fuels'. 

The only thing that remains is the principle of depending on forc whilst developing fuels-rs, which we kind of already do since you can't actually run the tests without running forc beforehand.

**Comment by Voxelot** [comment]
This is true as long as forc is only required as a dev-dep and seems worth trying out. I don't have enough context in the SDK to know what parts of the internal test harness may be publicly reused in other places though.

**Comment by hal3e** [comment]
closed with https://github.com/FuelLabs/fuels-rs/pull/838
