### ISSUE TITLE
Add TxParams to transfer

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuels-rs#270]
[`Wallet::transfer`](https://github.com/FuelLabs/fuels-rs/blob/v0.11.0/packages/fuels-signers/src/wallet.rs#L143) doesn't support customization of fee parameters. This is needed to be able to use the SDK against production environments.

**Comment by QuinnLee** [comment]
Created https://github.com/FuelLabs/fuels-ts/issues/255 to track this on the ts side
