### ISSUE TITLE
Remove `lw` when forwarding `amount` on contract call

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-rs#285]
Doing changes on `fuels-ts` https://github.com/FuelLabs/fuels-ts/pull/277 we notice that, `lw` implemented on #174 to forward `amounts` up to `u64` is not needed. Anymore.

**Comment by adlerjohn** [comment]
`fuels-rs` uses a lower-level call script that `fuels-ts`. It needs to get the amount to forward from script data into a register, so it has to use `LW`. `fuels-ts` can avoid this if it casts in a Sway asm block (which implicitly uses `LW`), but `fuels-rs` doesn't have any Sway code so it can't do this.

**Comment by luizstacio** [comment]
> `fuels-rs` uses a lower-level call script that `fuels-ts`. It needs to get the amount to forward from script data into a register, so it has to use `LW`. `fuels-ts` can avoid this if it casts in a Sway asm block (which implicitly uses `LW`), but `fuels-rs` doesn't have any Sway code so it can't do this.

Should we close this issue?

**Comment by adlerjohn** [comment]
Yes 😂
