### ISSUE TITLE
Add documentation on setting up account with Ether

### ISSUE THREAD

**Issue by SilentCicero** [FuelLabs/fuels-rs#287]
We should have an easy getting started page of somekind which tells the developers how they startup their fuel project with some test ether balance.

To answer this:
https://discord.com/channels/732892373507375164/734213700835082330/976107740990672957

**Comment by digorithm** [comment]
I believe this was solved by the recent doc re-org, here: https://github.com/FuelLabs/fuels-rs/blob/master/docs/src/wallets/test-wallets.md#setting-up-multiple-test-wallets. Which looks like this: 
<img width="691" alt="image" src="https://user-images.githubusercontent.com/3484025/178570641-3e50e00d-f55e-4980-8115-f56ecea2bf28.png">


If that's not enough to solve this issue let me know so we can re-open it, and I can make some improvements to it!
