### ISSUE TITLE
Update the book to use the latest version to match the code in the subsequent pages

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/fuels-rs#298]
[Here](https://fuellabs.github.io/fuels-rs/latest/getting-started/setup.html#importing-the-fuel-rust-sdk) is the section mentioning which versions to use (version 12).
The subsequent page seems to use code from version 13.

The book should be reviewed / updated to make sure that the versions match and that the code works.

**Comment by vnepveu** [comment]
This issue is linked to https://github.com/FuelLabs/sway/1577.
