### ISSUE TITLE
Make contract calls with structs as inputs work

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/fuels-rs#30]
As of now, contract calls with structs as inputs don't work because of the way we're crafting the `script_data` and `script` being passed to the transaction. 

We need to develop a way to read custom types in contract calls.

**Comment by adlerjohn** [comment]
Is this an issue with the SDK, or the script you're constructing?

**Comment by digorithm** [comment]
> Is this an issue with the SDK, or the script you're constructing?

The script, I believe. Or how accessing custom types in the VM works. I'm in talks with @vlopes11 to figure this out.
