### ISSUE TITLE
Allow some deps of fuels to be optional

### ISSUE THREAD

**Issue by tjsharp1** [FuelLabs/fuels-rs#317]
`fuels-contract`, `fuels-signers` and `fuels-test-helpers` all have dependencies that don't compile to WASM.
It would be nice to have these as optional dependencies so they don't have to be compiled for a WASM target.

Really all the indexer needs is the type definitions out of the contract ABI, as well as `Tokenizable`, `ParamType` and the other types necessary to deserialize.

**Comment by digorithm** [comment]
Isn't this related to https://github.com/FuelLabs/fuels-rs/issues/62?

**Comment by hal3e** [comment]
@segfault-magnet recently introduced a `std` flag in `fuels` which makes it wasm compatible.
