### ISSUE TITLE
Using an `Address` as a type inside a locally defined struct errors when passed into a function

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/fuels-rs#326]
The following

```
contract;

use std::address::Address;

struct User {
    address: Address,
    weight: u64
}

abi MyContract {
    fn test_function(user: User) -> bool;
}

impl MyContract for Contract {
    fn test_function(user: User) -> bool {
        true
    }
}
```

produces
![1](https://user-images.githubusercontent.com/103777923/170499457-7824d257-20b3-4e78-809d-a1d43ccc0c5a.png)

The issue is the `User` struct contains an `Address`.
Defining a local struct that contains a boolean and replacing the `Address` for that local struct does not cause issues. This seems specific to the `Address` and not structs in general.

Note: Passing in `Address` as the parameter type instead of `User` works as expected.

When changing the code above make sure to run `forc clean` each time before you `forc test` otherwise issues sometimes do not pop up.

**Comment by Voxelot** [comment]
Related to https://github.com/FuelLabs/fuels-rs/issues/323
