### ISSUE TITLE
Support for predicates

### ISSUE THREAD

**Issue by simonr0204** [FuelLabs/fuels-rs#341]
The Fuel VM allows for a Coin or Message input to be locked behind a predicate. To spend one of these inputs, the predicate is provided as a field of the input. If `hash(predicate) == Input.owner && eval(predicate)` , the UTXO can be spent. Note that in this case, no signature is required as the predicate alone is sufficient to spend the UTXO.

The SDK will therefore need to be able to:
- attach a compiled predicate to an Input.
- attach predicate data to an input. (This is analagous to providing scriptdata to a script - the data are parameters to the main function)
- send a transaction without the need for any wallet or signer
- set an output's `owner` to the hash of a compiled predicate

**Comment by simonr0204** [comment]
I'm reluctant to attach a priority label to this, but it's right on the critical path for getting the bridge mechanism working. I'll let @adlerjohn decide what level to assign.

**Comment by adlerjohn** [comment]
Note that a lot of predicates will essentially be "verify this signature over the tx" but with a slightly different signature. So the SDK will need to allow signing transactions in ways that aren't the canonical signature form.
