### ISSUE TITLE
feat: the SDK should differentiate `invalid transactions` and `reverting transactions` 

### ISSUE THREAD

**Issue by iqdecay** [FuelLabs/fuels-rs#345]
There are 3 states:
1. The transaction is invalid or the node is offline,
2. The transaction is valid, but reverts,
3. The transaction is valid, and executes to completion.

With #324, even if logging and debugging was improved, we are still bundling `1.` and `2.` together, whereas we want them to be differentiated.

**Comment by MujkicA** [comment]
If #411 is implemented to use `Transaction::validate_without_signature()`, the first case should be covered.
As for the second case: 
When a contract call fails, we receive `TransactionStatus::Failure` where the field `program_state` is set to the variant `Revert` if a a RVRT instruction was run.
