### ISSUE TITLE
Enums with different variant widths are not properly handled on the ABI interface

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/fuels-rs#352]
For example, if my enum looks like:
```rust
enum SomeEnum {
    V1: b256,
    V2: u64
}
```
and then I pass `SomeEnum::V2(42)` as an argument to a contract method from the SDK, the SDK is actually sending 2 words (tag + `u64`) and not 5 (tag + 4 words because `b256` is the largest variant).

The reason why this matters is because the compiler is expecting 5 words as it has to account for the largest possible enum that can be sent. When the contract method has multiple arguments, the compiler can get confused if that size is not respected by the SDK (the compiler assumes 5 words and it starts reading into the next argument etc.) 

I think the SDK should do the following:
* Write the tag which is 1 word
* Write the value
* Write zeros until we reach the max possible number of words which is basically `1 + size_of(largest variant)`

**Comment by segfault-magnet** [comment]
blocked by: FuelLabs/fuel-specs#339
blocked by: FuelLabs/sway#1872
