### ISSUE TITLE
`Vec` and heap type support

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/fuels-rs#353]
# Description

Currently, the SDK only supports static-sized arrays in the format `[T; n]` where `T` is the type and `n` is the length. 

Soon, Sway will release `Vec`, a growable/mutable/dynamic vector. We need to support this on the SDK side.

# Blockers

- [x] https://github.com/FuelLabs/sway/pull/1118: Full `Vec` support in Sway
- [x] https://github.com/FuelLabs/sway/issues/1994: An output-related work that needs to be done in the compiler, i.e., converting the heap data into stack data and returning it in a `retd`
- [x] https://github.com/FuelLabs/sway/issues/1993: Additional type-related data in the JSON ABI needs to be outputted by the compiler (the `T` in `Vec<T>` needs to be resolved and present in the ABI)
- [x] https://github.com/FuelLabs/sway/issues/2386
- [x] https://github.com/FuelLabs/fuels-rs/pull/587
- [x] https://github.com/FuelLabs/sway/issues/2900
- [x] https://github.com/FuelLabs/fuels-rs/issues/600

# Design

`Vec` is implemented in Sway with a struct like this:

```Rust
struct RawVec<T> {
    ptr: u64,
    cap: u64,
}

pub struct Vec<T> {
    buf: RawVec<T>,
    len: u64,
}
```

Once a Sway user imports it into their contract, `Vec<T>` and `RawVec<T>` will be exposed in the JSON ABI as regular structs. This will be `abigen!`'d on the SDK side, turning these two Sway structs into equivalent Rust structs.

Passing data in and out using `Vec` will be the most challenging part. 

Passing in a `Vec<T>` to a contract call in Rust-land means we have to encode the length `len`, the pointer `ptr`, and the capacity `cap`. But where is the `ptr` pointing to? It will point to where the data lives _inside the `script_data`_, where we'll have to encode the actual content of the `Vec<T>`. This should suffice and, in Sway-land, a user should be able to access the contents of the `Vec<T>` param in their contract method. 

Taking the returned data, in Rust-land, from a contract call that returns a `Vec<T>` means [this](https://github.com/FuelLabs/sway/issues/1994), which should be simpler than the encoding part.

Once the SDK is unblocked by the compiler, the SDK needs to encode the vector data into `script_data` and point to it using the `Vec`'s `ptr`. 

## Update August 16th, 2022

We've decided to support only `Vec` as inputs for now. Once that's done, `Vec` as output will be effectively a log of its data in the `Receipt`s.

**Comment by digorithm** [comment]
Reopening to use this as a tracker for the `vec` _output_ support (https://github.com/FuelLabs/fuels-rs/issues/602).

**Comment by iqdecay** [comment]
Support for `Vec` was added in #848, support for bytes was added in #868.
Support for those types as script returns will be tracked in #866.
