### ISSUE TITLE
Fuel Rust SDK book re-org

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/fuels-rs#365]
# Problem

Currently, the `fuels-rs` book, although it has plenty of information, it is poorly organized, making it really hard to find information as a user, especially as a beginner. We have been basically dumping all we know about it without much thought, which is fine for starters but has grown to be hard to use.

It also lacks _some_ sections, such as types (i.e. how do my types defined in Sway show up in rust-land? How about Sway-native types?), providers, and more fundamentals.

# Proposal

To begin addressing this, we must first rethink the outline of the documentation. Then, once we have each chapter/section defined, we can work in parallel.

Here's the initial re-org of the documentation, I'll update it as we discuss:

- [x] Getting started
  - [x] Setup
  - [x] Terminology (briefly explains contracts, providers, wallets/signers, etc.)
  - [x] Contracts (the very basics of contracts in the SDK, no advanced usage)
  - [x] Wallets and signing 
  - [x] Types (explains how `abigen!` works, at a high level, and how it generates the types coming from Sway contracts)
- [x] API (I'll will actually point to the rust docs and improve these rustdocs)
  - [x] Providers
  - [x] Wallets
  - [x] Contracts (focus on configuration stuff such as txparams, call params, contracts calling other contracts, and more)
  - [x] Utilities and helpers (more in-depth around the test helpers, logging, encoding/decoding data, etc.)
- [ ] Cookbook (more complete examples, probably coming from bigger examples in the `examples/` crate)
- [ ] Debugging (a whole chapter dedicated to some debugging practices we use)
  - [ ] Debugging abigen errors (talk about using `cargo-expand` to expand macros, etc)
  - [ ] Debugging contract call errors (network call worked, but contract code failed in the VM)
  - [ ] Debugging network call errors
- [ ] Testing

Once we settle with an outline, I'll turn these into checkboxes and we can work on each of them at the appropriate pace.

cc @vnepveu @MujkicA @segfault-magnet @Salka1988 @hal3e @Br1ght0ne @adlerjohn @SilentCicero

**Comment by vnepveu** [comment]
I really like this first outline! Seems progressive enough.

**Comment by adlerjohn** [comment]
Looks good!
