### ISSUE TITLE
Allow disabling default features for fuel-tx

### ISSUE THREAD

**Issue by tjsharp1** [FuelLabs/fuels-rs#371]
When attempting to disable default features for fuel-tx, I get a compile error.
```
error[E0432]: unresolved import `fuel_tx::Receipt`
 --> packages/fuels-core/src/errors.rs:4:5
  |
4 | use fuel_tx::Receipt;
  |     ^^^^^^^^^^^^^^^^ no `Receipt` in the root

For more information about this error, try `rustc --explain E0432`.
error: could not compile `fuels-core` due to previous error
```

For WASM, we'll need receipt types, so I'll leave the dependency as-is for now. But it would be nice to get it working with disabling default features as well, so we're not pulling in extra stuff.

**Comment by Salka1988** [comment]
It seems that this problem occurs only on Macs. @MujkicA - You are using a Mac so can you take a look?

**Comment by Br1ght0ne** [comment]
As I am working on #429, will be changing features of `fuel-tx`, and have a Mac, I'll assign this to me for now. Thanks @Salka1988 :)

**Comment by Br1ght0ne** [comment]
Setting `default-features = false` for `fuel-tx` in `fuels-core/Cargo.toml` compiles and works for me on latest master (48076911) on an M1 MacBook Pro. I'll see if this is still an issue.

**Comment by Br1ght0ne** [comment]
Verified that `fuel_tx::Receipt` is still there on `default-features = false`. Closing.
