### ISSUE TITLE
Implement storage initialization in the SDK

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/fuels-rs#401]
The JSON format spec for storage initialization is now ready: https://github.com/FuelLabs/fuel-specs/blob/master/specs/protocol/storage_initialization.md

The compiler will emit this file (task tracked in https://github.com/FuelLabs/sway/issues/1185) and the SDK read that file and set the initial storage slots in the contract creation tx.

**Comment by digorithm** [comment]
I think this was already documented here: https://github.com/FuelLabs/fuels-rs/issues/87

**Comment by mohammadfawaz** [comment]
Ohhhh alright, I'll let you handle organizing these issues then. Feel free to close this one :)

**Comment by digorithm** [comment]
Sounds good, I'll update the original one with the new info from this one -- thanks!
