### ISSUE TITLE
Use new `fuel-core` APIs to get transaction consensus parameters and minimum gas fee

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/fuels-rs#411]
Some transaction-related configurations in the SDK are either hardcoded or not checked at all. For instance, the `transaction_parameters` passed to the chain config below:

https://github.com/FuelLabs/fuels-rs/blob/054f352216f2327b36b20b884453787ce30166bc/packages/fuels-test-helpers/src/node.rs#L174-L197

There are currently no checks for these `max_*` configurations on the SDK end. We don't have it because we didn't have a way to dynamically query that from the node, [now we do](https://github.com/FuelLabs/fuel-core/pull/373), using: `client.chain_info()`. So these should be queried and checked when creating a new transaction.

Another configuration that should be dynamically checked is the minimum gas price. Which can now be queried through the `Client`'s `node_info()`.

We should use these constraints (`max_*`, `min_*`, etc.) when setting these values and properly handle errors.

**Comment by MujkicA** [comment]
To get finer grained error handling as required by #249 and #345 we would need to check the transaction for validity on the SDK side. IIUC, `Transaction::validate_without_signature()` checks both the consensus parameters and validity e.g no duplicate inputs.  
We get two birds with one stone if we check  'validate_without_signature()' before submitting transactions to the VM.
One problem is that validation requires the current `block_height` to check if the required `maturity` is met, so we would need to connect it with #410 at some point.
