### ISSUE TITLE
EvmAddress not fully supported ?

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/fuels-rs#434]
I'm not sure what the root cause of this is, but:
I have a contract abi function which returns an EvmAddress :
```
fn layer1_token() -> EvmAddress {
        ~EvmAddress::from(LAYER_1_TOKEN)
 }
```
where `LAYER_1_TOKEN = 0x0000000000000000000000000000000000000000000000000000000000000000;`

My test looks like this:
```
#[tokio::test]
        async fn can_get_layer_1_token() {
            let (instance, _id) = setup().await;
            let call_response = instance.layer1_token().call().await.unwrap();
            let dummy_layer_1_token = EvmAddress { value: [0u8; 32] };
            assert_eq!(call_response.value, dummy_layer_1_token);
        }
```
and fails with an `OutOfMemory` error.
However, if I leave the test as is and modify the function to be this:
```
fn layer1_token() -> b256 {
   LAYER_1_TOKEN
}
```
then the test passes.
This test also seems to work fine if I switch the contract function return type to be an `Address`.

### Steps to reproduce:
Copy-paste the code below into a new `forc` project, build the contract and run the test.

**main.sw:**
```
contract;

use std::vm::evm::evm_address::EvmAddress;

abi EvmTest {
    fn test_function() -> EvmAddress;
}

impl EvmTest for Contract {
    fn test_function() -> EvmAddress {
        ~EvmAddress::from(0x0000000000000000000000000000000000000000000000000000000000000000)
    }
}
```

**harness.rs:**
```
use fuels::{prelude::*, tx::ContractId};

// Load abi from json
abigen!(EvmAddressTestContract, "test_projects/bug_repro/out/debug/bug_repro-abi.json");

async fn get_contract_instance() -> (EvmAddressTestContract, ContractId) {
    // Launch a local network and deploy the contract
    let wallet = launch_provider_and_get_single_wallet().await;

    let id = Contract::deploy("test_projects/bug_repro/out/debug/bug_repro.bin", &wallet, TxParameters::default())
        .await
        .unwrap();

    let instance = EvmAddressTestContract::new(id.to_string(), wallet);

    (instance, id)
}

#[tokio::test]
async fn test_function_with_evm_address_return() {
    let (instance, _id) = get_contract_instance().await;
    let res = instance.test_function().call().await.unwrap();
    assert_eq!(res.value, EvmAddress { value: [0u8; 32] });
}

```

**Comment by segfault-magnet** [comment]
@nfurfaro 
I've reproduced the issue -- it turns out the `MemoryOverflow` happens even without the SDK.

If you deploy this contract and then run a script calling it via `forc run` you'll get the same result meaning that this doesn't have anything to do with the SDK. 

I'll upload a minimum reproduction to a separate repo and ask for directions from the Sway/vm-client team.
