### ISSUE TITLE
build currently broken -- CI always uses the feature `fuel-core-lib`

### ISSUE THREAD

**Issue by segfault-magnet** [FuelLabs/fuels-rs#435]
If we run `cargo build --no-default-features` we'll get:
```
error[E0425]: cannot find function `is_free` in this scope
   --> packages/fuels-test-helpers/src/lib.rs:192:52
    |
192 |         Some(config) if config.addr.port() != 0 && is_free(config.addr.port()) => config.addr,
    |                                                    ^^^^^^^ not found in this scope
    |
help: consider importing this function
    |
3   | use portpicker::is_free;
    |

error[E0425]: cannot find function `is_free` in this scope
   --> packages/fuels-test-helpers/src/lib.rs:193:26
    |
193 |         Some(config) if !is_free(config.addr.port()) => panic!("Error: Address already in use"),
    |                          ^^^^^^^ not found in this scope
    |
help: consider importing this function
    |
3   | use portpicker::is_free;
    |

For more information about this error, try `rustc --explain E0425`.
error: could not compile `fuels-test-helpers` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

It seems that our CI always runs `fuels-rs` with `--all-features` which renders some of the code disabled due to the conditional compilation based on the flag 'fuel-core-lib`. As such we have parts of our code that are basically unchecked by the CI.

Fix the CI and make the build pass.

Ideally, we'd have a test run with fuel-core as a lib and another one with it as a binary, for maximum regression protection.

**Comment by digorithm** [comment]
> Ideally, we'd have a test run with fuel-core as a lib and another one with it as a binary, for maximum regression protection.

Yes, my only concern here is that the CI time could increase significantly 🤔 

As for the issues w.r.t feature flag, I'm pinging the `fuel-core-lib` flag creator @Salka1988.

**Comment by segfault-magnet** [comment]
Perhaps  @Salka1988 can measure the impact? At the very least we need a cargo check without the feature to keep it buildable.
