### ISSUE TITLE
deps: get better view of the deps, solve the `fuels-types` dependency of Sway

### ISSUE THREAD

**Issue by iqdecay** [FuelLabs/fuels-rs#446]
- Currently it's hard to see what the dependency cycles are, and what refactoring does to the deps graph. We need to find a way to reliably visualize this
- We import `fuels-types` pretty much everywhere where `fuels-core` is imported too, maybe it should be a re-export? 
- The Sway repository currently imports the `fuels-types` workspace, which is not ideal when Sway team wants to update some things on it.

**Comment by digorithm** [comment]
I believe this isn't relevant anymore, so I am closing it for now!
