### ISSUE TITLE
test: parse JSON ABI for function selectors and argument encoding

### ISSUE THREAD

**Issue by iqdecay** [FuelLabs/fuels-rs#464]
Currently, we are "building" JSON ABIs by chaining `Property`s together (eg `fn_selector_nested_custom_types`). This in fine in theory, but in practice it means that we don't really base our signatures/selectors/arguments on the Forc output.
- We should find a way to parse JSON ABI directly into a `Vec<Property>` so that these properties are not built "by hand". This way we can avoid having regressions going under the radar when the ABI or encoding changes.

**Comment by segfault-magnet** [comment]
This can probably be closed. Doesn't seem to resemble the current implementation at all. 

@iqdecay @digorithm

**Comment by iqdecay** [comment]
Agreed, closing as it is now obsolete.
