### ISSUE TITLE
SDK setting wrong param2 value in call frames

### ISSUE THREAD

**Issue by matt-user** [FuelLabs/fuels-rs#465]
When calling contract functions that return their own list of parameters a function with no parameters returns a non-zero value.

**Comment by adlerjohn** [comment]
If there are no parameters, then the value of `param2` is meaningless. It could be anything and that would technically be valid.

**Comment by matt-user** [comment]
I see, so should we just not test this case?

**Comment by adlerjohn** [comment]
Given that the entire space is valid, I don't even see how you could test it! Closing as wontfix.
