### ISSUE TITLE
abigen! fails to get b256 type when it is with another reference type as a parameter

### ISSUE THREAD

**Issue by matt-user** [FuelLabs/fuels-rs#470]
If b256 is with another reference type as a parameter abigen cannot resolve the b256 type. [repro](https://github.com/matt-user/repro)

**Comment by digorithm** [comment]
More context: Just checked the expanded types from the abigen, I think it’s related to tuples:

```Rust
 pub fn dummy(
            &self,
            arg_0: TestStruct,
            arg_1: [u8; 32],
        ) -> ContractCallHandler<(TestStruct, b256)> {}
```
`b256` should’ve been expanded to an array, like it does when not in a tuple.
