### ISSUE TITLE
'Instantiating a Fuel client' example in book not working

### ISSUE THREAD

**Issue by seem-less** [FuelLabs/fuels-rs#473]
It seems that the example '[Instantiating a Fuel client](https://fuellabs.github.io/fuels-rs/v0.17.0/getting-started/basics.html#instantiating-a-fuel-client)' does not compile because the `node` module is not part of the `fuels` crate.

`use fuels::node::service::{Config, FuelService};`

It seems that the required types are actually in the `fuels_test_helpers` crate instead

**Comment by vnepveu** [comment]
Do you mind providing a repro please? I can't seem to make it fail locally, and *normally* (though CI works in mysterious ways), the docs should be tested by CI.

**Comment by seem-less** [comment]
I created a new library with `cargo` and then following the [Setup Instructions](https://fuellabs.github.io/fuels-rs/v0.17.0/getting-started/setup.html) my files look like this:

`Cargo.toml`
```
[package]
name = "rust-sdk-example"
version = "0.1.0"
edition = "2021"

[dependencies]
fuels = "0.17"
```

`src/lib.rs`
```
use fuels::prelude::*;

async fn instantiate_client() -> Result<(), Error> {
    use fuels::client::FuelClient;
    use fuels::node::service::{Config, FuelService};

    let server = FuelService::new_node(Config::local_node()).await?;
    let client = FuelClient::from(server.bound_address);
    assert!(client.health().await?);
    Ok(())
}
```

It seems that if the `fuel-core-lib` feature is enabled on the `fuels` crate, the required imports are provided by the `fuels::prelude::*`, which means that the separate import of `Config` and `FuelService` would not be required.

**Comment by vnepveu** [comment]
Can you try runnig with `--features fuel-core-lib` flag please?

**Comment by Salka1988** [comment]
`use fuels::node::service::{Config, FuelService};` is not exposed anymore and     
`let server = FuelService::new_node(Config::local_node()).await?;` needs fuel-core-lib flag.

I will take this issue and we can discuss it today
