### ISSUE TITLE
Create `ContractId` and `LocalWallet` getters for the generated contract struct

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/fuels-rs#485]
Currently, the generated contract struct has the `ContractId` and `LocalWallet` as private fields:

```Rust
// ...
quote! {
  pub struct #name {
      contract_id: ContractId,
      wallet: LocalWallet
  }
// ...
```

It would be useful to have an `abigen`-generated getter for those fields so users could easily access them.

**Comment by simonr0204** [comment]
Could we also get one for the wallet? :D

**Comment by digorithm** [comment]
> Could we also get one for the wallet? 😁

Don't we already have a getter for a wallet's address? 

https://github.com/FuelLabs/fuels-rs/blob/b00a3a707c2013bf2a5dc331dfb1b4052a00b522/packages/fuels-signers/src/lib.rs#L32

Unless you mean something else 😅
