### ISSUE TITLE
feat: allow starting the node binary with custom parameters

### ISSUE THREAD

**Issue by iqdecay** [FuelLabs/fuels-rs#489]
For instance starting the node with `manual_blocks_enabled` so the `produce_blocks` API can be used.

**Comment by hal3e** [comment]
@camsjams has extended the config with `predicates` and `utxo-validation` in https://github.com/FuelLabs/fuels-rs/pull/432.
I have then refactored the code to take the whole config when running the node and extract the enabled flags in https://github.com/FuelLabs/fuels-rs/pull/527
