### ISSUE TITLE
Possible to setup a wallet with coins for an existing Fuel node?

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuels-rs#500]
- Referencing the "connect to external node" docs [here](https://fuellabs.github.io/fuels-rs/v0.18.0/providers/external-node.html)
- I have an external Fuel node that I would like to connect to, deploy a contract, and interact with that contract
- I was thinking I would use `setup_single_asset_coins` and something similar to `setup_test_client` -- but obviously `setup_test_client` is for creating a _new_ Fuel node
- Do I need to create a custom `Config`  using coins from `setup_single_asset_coins`, with that `Config` having a `ChainConfig` that references the existing Fuel node?
- I apologize if I'm not even asking this question the proper way

Additional context
- The use case here is that on the fuel-indexer project, I'm trying to create a small test environment where we can check that all the indexer components work together
- This test environment would consist of a Fuel node container, an indexer container, and an app/http container
  - The http container (a small http API that ) will receive a request and submit a transaction to the Fuel node container
  - The Fuel node container will submit the output of the transaction to the indexer container -- which will index the event
- As of now, I test this thing locally -- but as we continue to productionize the indexer, I'll need a more formal way of testing this (by connecting to an existing Fuel node)

**Comment by iqdecay** [comment]
Ultimately, what you're precisely asking is impossible: it is equivalent to "minting" assets out of nowhere. If on the Fuel node you don't have any coins at that wallet's address, then it is _fortunately_ impossible to generate them after.
However, you can set-up your external node to have some coins at a given address when starting it. If the `fuel-core` docs do not explain it, you can probably take a look at how we implemented the `setup_single_asset_coins` to start the node with the corresponding options.
I'm closing this as it's not related to the SDK, you're using an external node.

**Comment by MujkicA** [comment]
I'm not sure if it fits the use case, but AFAIK you could mint assets via a contract and use it to fill you wallets for testing:

[Native Token Example](https://fuellabs.github.io/sway/v0.16.2/blockchain-development/native_assets.html?highlight=mint#native-token-example)
[Swayswap token contract](https://github.com/FuelLabs/swayswap/blob/master/packages/contracts/token_contract/src/main.sw)

**Comment by ra0x3** [comment]
> However, you can set-up your external node to have some coins at a given address when starting it
- This is essentially what I was referring to(sorry if my description wasn't too great), I think `setup_single_asset_coins` might have what I need

Thanks @MujkicA 👌
