### ISSUE TITLE
test failed with fuels-core-lib 0.18.0

### ISSUE THREAD

**Issue by zoey-t** [FuelLabs/fuels-rs#504]
I created a new project via `forc new` and update the fuel-core-lib to 0.18 in Cargo.toml as it suggested
test failed with this version
![image](https://user-images.githubusercontent.com/101599447/181622699-022762ea-6959-4be5-bce1-a10288163d52.png)

**Comment by iqdecay** [comment]
Hi! 
Can you please give us:
- Your `Cargo.toml`
- Your `Forc.toml`
- The output of:
```forc --version```

**Comment by zoey-t** [comment]
> Hi! So I have indeed been able to repro with the following `Cargo.toml` (notice that it is `fuels` set to `0.18` and not `fuel-core-lib`):
> 
> ```toml
> [project]
> name = "bimbam"
> version = "0.1.0"
> authors = ["xxxxx"]
> edition = "2021"
> license = "Apache-2.0"
> 
> [dependencies]
> fuels = { version = "0.18", features = ["fuel-core-lib"] }
> tokio = { version = "1.12", features = ["rt", "macros"] }
> 
> [[test]]
> harness = true
> name = "integration_tests"
> path = "tests/harness.rs"
> ```
> 
> Then, running `forc test` fails. It does _not_ fail when setting `fuels=v0.17`.

yeah. it fails when version is 0.18

**Comment by iqdecay** [comment]
The solution for you is simply, for the harness, to do: 
```rust
use fuels::{prelude::*, tx::ContractId};

// Load abi from json
abigen!(MyContract, "out/debug/bimbam-abi.json");

async fn get_contract_instance() -> (mycontract_mod::MyContract, ContractId) {
    // Launch a local network and deploy the contract
    let wallet = launch_provider_and_get_wallet().await;

    let id = Contract::deploy(
        "./out/debug/bimbam.bin",
        &wallet,
        TxParameters::default(),
        StorageConfiguration::with_storage_path(Some(
            "./out/debug/bimbam-storage_slots.json".to_string(),
        )),
    )
    .await
    .unwrap();

    let instance = MyContractBuilder::new(id.to_string(), wallet).build();

    (instance, id)
}

#[tokio::test]
async fn can_get_contract_id() {
    let (_instance, _id) = get_contract_instance().await;

    // Now you have an instance of your contract you can use to test each function
}

```
The fix has to be done directly on the Sway repo (we're generating a wrong harness with `forc new`, will update when merged/released.
