### ISSUE TITLE
enable skipped test in harness.rs

### ISSUE THREAD

**Issue by hal3e** [FuelLabs/fuels-rs#509]
In the PR https://github.com/FuelLabs/fuels-rs/pull/506 we skipped the test on
`fn take_array_string_return_single_element(a: [str[3];3]) -> str[3];` as it results in a compiler error.
We should wait until https://github.com/FuelLabs/sway/issues/2410 is resolved and then enable it.

**Comment by iqdecay** [comment]
Good thinking to track it in an issue!
