### ISSUE TITLE
`InputMessage` support

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/fuels-rs#530]
The new bridge design ([https://github.com/FuelLabs/bridge/blob/master/docs/design_docs.md](https://github.com/FuelLabs/bridge/blob/master/docs/design_docs.md)) has introduced the concept of `InputMessage` and `OutputMessage`. 

Messages will effectively act as coins (as well as other functionalities), meaning that users can select a message, which contains a value in it, and use it to pay for transaction costs, instead of using their own (non-message) coins for that. 

The SDK needs to support that. It needs to:

1. Allow users to query/filter the messages they own;
2. Attach a selected message to a contract call — this, if enabled, should replace the need to select spendable coins for the transaction costs.

The design details of the API for querying/filtering messages and attaching them to contract calls are still open for discussion.

For testing purposes, you might want to add messages to a local development chai, similarly to what we do for coins: adding them through the chain config, and spawning a local test chain with this config. This is possible through the chain config, so it shouldn’t be a problem to set up a test chain with pre-configured messages for your `InputMessage`-related tests.

The `InputMessage` struct / graphql schema should be accessible through `fuel-core`.

**Comment by Salka1988** [comment]
Im blocked by https://github.com/FuelLabs/fuels-rs/issues/537. As soon as we merge this issue, I will continue with the task, and the code is already cooking.
