### ISSUE TITLE
Use gas estimation when requiring spendable coins of the base asset.

### ISSUE THREAD

**Issue by segfault-magnet** [FuelLabs/fuels-rs#536]
When requesting spendable coins from the node to construct the contract-calling script, don't use the huge default but try to incorporate the work done [here](https://github.com/FuelLabs/fuels-rs/issues/514) to estimate the transaction cost and request only the minimal amount needed to cover the gas price.

Potentially include a tolerance to account for gas price fluctuations.

**Comment by MujkicA** [comment]
Blocked by #537
