### ISSUE TITLE
ABIgen should conform to `rustfmt`

### ISSUE THREAD

**Issue by iqdecay** [FuelLabs/fuels-rs#54]
Currently, the ABIgen-generated Rust-code doesn't conform to `rustfmt`. It's not a pressing issue for now but this should be solved in the long-run (eg. for tests generation it could be problematic).

**Comment by segfault-magnet** [comment]
@digorithm @iqdecay Do we still want this? 

The effort needed to achieve this is non-neglectable, but protecting against regressions would be even harder.

If the abigen-ed code ever stops being generated by a macro, then it is up to the owners to format them in whatever way they wish. We cannot predict their rustfmt config.
