### ISSUE TITLE
fix: investigate if we need a `seen` hashmap for expanding Enums

### ISSUE THREAD

**Issue by iqdecay** [FuelLabs/fuels-rs#542]
For expanding structs, we currently check that they have not been already expanded using a `seen` vec, we should investigate if we need it for Enums as well.

**Comment by digorithm** [comment]
I already added in here: https://github.com/FuelLabs/fuels-rs/pull/533/files#diff-2e19366751db132fe569ebbcf6185f4bd93501024caebf4d1e610fcea34297f6R238.

**Comment by iqdecay** [comment]
Closing per above comment :)
