### ISSUE TITLE
Suggestion: Consider removing the `LocalWallet` type alias and use `Wallet` instead

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/fuels-rs#543]
The `LocalWallet` type alias kind of implies that the type itself has an API or implementation that is specific to local storage. The `LocalWallet` we have today is purely a type alias for `Wallet`, an in-memory construct that happens to provide a few methods for encrypting and decrypting to and from a local keystore. Even then, it appears these keystore paths are always passed as arguments and nothing to do with these paths are ever stored in the wallet instance itself.

I'd recommend removing `LocalWallet` and using `Wallet` directly, and perhaps reserving `LocalWallet` for some future implementation might be more narrowly tied to local storage.

**Comment by digorithm** [comment]
I'm not opposed to it. That was something inspired by `ethers-rs`, where it has its use, but I'm afraid it won't make much sense here. At least not for now.

**Comment by hal3e** [comment]
I will close the issue as this was merged in https://github.com/FuelLabs/fuels-rs/pull/540.
