### ISSUE TITLE
Expose the default derivation path to downstream crates

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/fuels-rs#551]
Currently downstream creates, which need to use the prefix of the default derivation path (like `forc-wallet`) are duplicating it. But we could expose the default derivation path from SDK (currently it is located [here](https://github.com/FuelLabs/fuels-rs/blob/ac2dc6eca8e1cc7db3d09c517cffea6d3c55d272/packages/fuels-signers/src/wallet.rs#L21)) so that it can be reused. Additionally, we may want to change the prefix to something like `m/44'/1179993420'/` so that it is a little more reusable.

Related to https://github.com/FuelLabs/forc-wallet/issues/28#issuecomment-1231181032

**Comment by iqdecay** [comment]
Was just thinking about this while working on the wallet as well!
