### ISSUE TITLE
Add specific testnet connection instructions to docs

### ISSUE THREAD

**Issue by simonr0204** [FuelLabs/fuels-rs#553]
With the testnet coming up, it would be a good idea to add specific instructions for how to connect to it (and maybe use the faucet) to the fuels-rs book. e.g. [here](https://fuellabs.github.io/fuels-rs/v0.21.0/providers/external-node.html) we already show how to connect to a local testnet. I know it's basically the same, but if there's one bit of code we want people to be able to copy/paste, it would be that.

**Comment by adlerjohn** [comment]
@digorithm can we have this done (or at least a preliminary version) by Monday?

**Comment by digorithm** [comment]
> @digorithm can we have this done (or at least a preliminary version) by Monday?

Yes, we should be able to get this quickly done tomorrow.
