### ISSUE TITLE
Enable passing in multiple contract IDs with a call

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/fuels-rs#59]
Currently calling a contract only sets add an input-output pair for that one contract ID. There are many cases where a transaction will want to call a contract that then calls another contract, and so on.

Support crafting a script transaction with multiple contract IDs as input-output pairs.

**Comment by nfurfaro** [comment]
@digorithm This issue was coming up in some of my tests last week, just wondering if it's something that might land soon, or if I should refocus on other things for a while?
