### ISSUE TITLE
Variable outputs estimation

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/fuels-rs#596]
Exactly like https://github.com/FuelLabs/fuels-rs/issues/595. Replace `Contract input set` for `variable outputs`. Same goals, design, and blockers.

**Comment by Voxelot** [comment]
How would the SDK know when there is not enough variable outputs? Would this be a special revert code returned by the std-lib?

**Comment by mohammadfawaz** [comment]
> Would this be a special revert code returned by the sway std-lib when it has exhausted all settable variable outputs?

We could certainly do this in https://github.com/FuelLabs/sway/blob/15b9d4322f35d7fb33f885bffd8d816371b3e9ca/sway-lib-std/src/token.sw#L108. However, the challenge will be know the *total* number of "missing variable output" instances. If a contract method has 5 calls to `transfer_to_output` for example (and no available variable outputs), the first one will revert (with some special error code) saying we're missing 1 variable output and that's it. That is, we won't get to account for the other reverts.

**Comment by MujkicA** [comment]
I think that is as good as we can expect. 
Same as for #595, we'll just have to retry on the SDK side until the number of outputs is satisfied.

**Comment by mohammadfawaz** [comment]
> Same as for https://github.com/FuelLabs/fuels-rs/issues/595, we'll have to retry on the SDK side until the number of outputs is satisfied.

Oh that's interesting. Okay then, that's satisfactory I suppose :)

**Comment by mohammadfawaz** [comment]
Is this reasonable: https://github.com/FuelLabs/sway/pull/2898?

**Comment by Voxelot** [comment]
There's also a risk that user contracts may arbitrarily choose these same revert codes, which may cause unexpected behavior in the SDK (like an infinite loop of adding new variable outputs).

**Comment by mohammadfawaz** [comment]
> There's also a risk that user contracts may arbitrarily choose these same revert codes, which may cause unexpected behavior in the SDK (like an infinite loop of adding new variable outputs).

True. We could also rely on a `log` here but that seems too expensive and confusing. We could disallow those error codes to be used in the `__revert()` intrinsic (ref https://github.com/FuelLabs/sway/pull/2890) but we'd have to do this at runtime and that could also get expensive.
