### ISSUE TITLE
Write tests at the component-level of the `abigen!`

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/fuels-rs#6]
Right now we have an end-to-end test suite for the `abigen!` under `fuels-abigen/tests/harness.rs`. 

But it would be _nice to have_ more granular tests at the level of each main component of the `abigen!`, for instance at the level of `custom_types_gen.rs`, where we generate custom types coming from the ABI. Or `functions_gen.rs`, where we generate the functions coming from the ABI.

**Comment by vnepveu** [comment]
Assigning myself because it will help me dig into the code more!

**Comment by digorithm** [comment]
Awesome! Yeah, this is a great issue to get a good feel on how things are happening in the codegen portion of the SDK.

**Comment by vnepveu** [comment]
Still some tests to write (they should be coming soon)

**Comment by vnepveu** [comment]
Was closed by #73 and #67
