### ISSUE TITLE
Vector as output

### ISSUE THREAD

**Issue by segfault-magnet** [FuelLabs/fuels-rs#602]
We've had a meeting with the compiler team where we agreed to the following:
* When returning or logging, vectors cannot be nested in other types.
* `retd` will be used to return vector data -- i.e. vector elements will be contained in the `ReturnData` receipt.
* `log`ging a vector will log its elements.

Currently, we've adapted the SDK to throw a compile-time error if it detects the usage of vectors in the output type of a contract method.

If somebody should circumvent that and call `ABIDecoder::decode...` on a vector or a type containing one, the SDK will panic with an appropriate message.

Blocked -- waiting for support from the compiler.

Related:
https://github.com/FuelLabs/sway/issues/2900
https://github.com/FuelLabs/fuels-rs/issues/600

**Comment by iqdecay** [comment]
Solved by #848 (I am going to add support for logging vectors because I didn't think of it at first)

**Comment by iqdecay** [comment]
Solved by #848.
Vector logging is tracked in #898
