### ISSUE TITLE
Remove --generate-logged-types flag from build script

### ISSUE THREAD

**Issue by MujkicA** [FuelLabs/fuels-rs#603]
We should remove the `--generate-logged-types` from our test projects build script once a new forc version is released. See: https://github.com/FuelLabs/sway/issues/2745

**Comment by mohammadfawaz** [comment]
`forc v0.25.1` is now available and _should_ hopefully have the necessary changes to unblock this. I know that upgrading to `forc v0.25.1` is blocked by something else, but hopefully that'll get fixed quickly.

**Comment by MujkicA** [comment]
Part of this issue was the removal of `--generate-logged-types` from our build script. We need to wait on a new forc version for this.

**Comment by mohammadfawaz** [comment]
I think this is now done in https://github.com/FuelLabs/fuels-rs/pull/627
