### ISSUE TITLE
Set custom timestamp on manually produced block

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/fuels-rs#606]
Currently, the SDK enables users to manually produce blocks. But, there's no way to set the timestamp of the to-be-produced block. The SDK should enable users to do that through its block-producing API.

Note that it needs to be supported by the client first (https://github.com/FuelLabs/fuel-core/issues/639).

**Comment by mohammadfawaz** [comment]
This is no longer blocked right? https://github.com/FuelLabs/fuels-rs/issues/606

**Comment by digorithm** [comment]
Yeah, this should be good to go!
