### ISSUE TITLE
Duplicated script test helper

### ISSUE THREAD

**Issue by simonr0204** [FuelLabs/fuels-rs#608]
[This function](https://github.com/FuelLabs/fuels-rs/blob/master/packages/fuels-test-helpers/src/script.rs#L18) is duplicated [here](https://github.com/FuelLabs/fuels-rs/blob/master/packages/fuels-test-helpers/src/script.rs#L33).

While we're there, could one of them be converted to take a `provider` so that we can test scripts against a node that's already been created? For example, a common pattern might be to deploy a couple of contracts and then run a custom script which interacts with them.

**Comment by digorithm** [comment]
They're not necessarily duplicates, they're under different feature flags. With `not` in it:
```
#[cfg(not(feature = "fuel-core-lib"))]
```

And without it:
```
#[cfg(feature = "fuel-core-lib")]
```

Maybe @Salka1988 could go in-depth and explain why this was necessary. 

> could one of them be converted to take a provider so that we can test scripts against a node that's already been created? 

This is a very valid request!

**Comment by simonr0204** [comment]
Oh, you're right! To my 9am eyes they were identical 😅

**Comment by Salka1988** [comment]
Nah, they are the same! I refactored them when i built ScriptBuilder but i forgot to delete one of them.

**Comment by digorithm** [comment]
> Nah, they are the same! I refactored them when i built ScriptBuilder but i forgot to delete one of them.

Ah, then one of them can go haha. Thanks @Salka1988!

**Comment by Salka1988** [comment]
> > Nah, they are the same! I refactored them when i built ScriptBuilder but i forgot to delete one of them.
> 
> Ah, then one of them can go haha. Thanks @Salka1988!

Should i make new function that accepts provider for our @simonr0204

**Comment by digorithm** [comment]
I would say extend the current by adding an `Option<Provider>`.
