### ISSUE TITLE
v0.24 breaks simple axum web handler routes

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuels-rs#615]
### Issue TLDR

- Upgrading to `fuelsv0.24` breaks `axum` routing to the point where testing is not possible in any capacity 
- `axum` is one of the most popular Rust web crates, so I (personally) think it's important that `fuels` work with `axum`
- If we cannot provide `axum` support, can we recommend a preferred web crate instead?

### Background
- Take a trivial sway conract
```sway
contract;

pub struct Ping {
    id: u64,
    value: u64,
    message: str[32],
}

abi FuelIndexer {
    fn ping() -> Ping;
}

impl FuelIndexer for Contract {
    fn ping() -> Ping {
        let p = Ping{
            id: 1,
            value: 123,
            message: "aaaasdfsdfasdfsdfaasdfsdfasdfsdf"
        };
        p
    }
}
```

- Previously (fuels 0.15), I would test this via the web with an axum web handler like so (leaving out some code for brevity)

```rust
abigen!(
    FuelIndexerTest,
    "path/to/my/fuel-indexer-test-abi.json"
);

async fn ping(Extension(contract): Extension<Arc<FuelIndexerTest>>) -> String {
    let result = contract.ping().tx_params(tx_params()).call().await.unwrap();
    let ping: Ping = result.value;
    ping.value.to_string()
}

async fn pong(Extension(contract): Extension<Arc<FuelIndexerTest>>) -> String {
    let result = contract.pong().tx_params(tx_params()).call().await.unwrap();
    let pong: Pong = result.value;
    pong.value.to_string()
}

# ...

 let state = Arc::new(contract);

let contract = FuelIndexerTest::new(contract_id.to_string(), wallet).build();

let app = Router::new()
        .route("/ping", post(ping))
        .layer(Extension(state.clone()))
        .route("/pong", post(pong))
        .layer(Extension(state.clone()));
```

- All of this worked fine and dandy, until upgrading to 0.24 -- which..for roughly the exact same code, won't pass `cargo check`, failing with error:

```text
error: higher-ranked lifetime error
   --> fuel-indexer-tests/components/web/src/bin/web-api.rs:121:25
    |
121 |         .route("/ping", post(ping))
    |                         ^^^^^^^^^^
    |
    = note: could not prove `fn(Extension<Arc<fuelindexertest_mod::FuelIndexerTest>>) -> impl Future<Output = std::string::String> {ping}: Handler<(Extension<Arc<fuelindexertest_mod::FuelIndexerTest>>,)>`

error: higher-ranked lifetime error
   --> fuel-indexer-tests/components/web/src/bin/web-api.rs:123:25
    |
123 |         .route("/pong", post(pong))
    |                         ^^^^^^^^^^
    |
    = note: could not prove `fn(Extension<Arc<fuelindexertest_mod::FuelIndexerTest>>) -> impl Future<Output = std::string::String> {pong}: Handler<(Extension<Arc<fuelindexertest_mod::FuelIndexerTest>>,)>`
```

- Unfortunately this code (axum with fuels v0.24) won't compile, so we cannot integrate two of the of the most important indexer testing components (`fuels` and `axum`)
- I do think that calling a smart contract via a web handler is an extremely popular thing to do. And with `axum` being one of the most (if not thee most) popular Rust web crate, I think maybe we should think about a fix for this?
- I have labeled this a "Question" since I don't think it's a bug
- Please let me know if you need any more info from me
- And what's more -- I can't even check our web component test into the repo (even if I don't use it) because `cargo check` won't pass 🥲

**Comment by iqdecay** [comment]
@ra0x3 can you please provide more context about how this was resolved so that people that go over the same question have an element? Even if it's very simple.
