### ISSUE TITLE
ci: `check-docs` does not work inside the `tests/scripts` directory

### ISSUE THREAD

**Issue by iqdecay** [FuelLabs/fuels-rs#640]
The `tests/scripts` directory was renamed `tests/script` because otherwise pointing to a file inside the directory was detected as non-existing by the `check-docs` script. Once this issue is fixed, the directory can be renamed to `scripts`.

**Comment by hal3e** [comment]
Most likely related to this line: https://github.com/FuelLabs/fuels-rs/blob/4807691155f5ede1723f41c27d2c0e3c0206d407/scripts/check-docs/src/lib.rs#L188

**Comment by iqdecay** [comment]
Yes but couldn't figure out for the life of me how to change it haha.

**Comment by Salka1988** [comment]
Is this fixed? @iqdecay

**Comment by hal3e** [comment]
We do not have the `scripts` folder any more so it works, but I fixed it in a branch and forgot to assign this to me. I will push a PR
