### ISSUE TITLE
docs: incorrect wording in "Connecting to a Fuel Node" Page

### ISSUE THREAD

**Issue by matt-user** [FuelLabs/fuels-rs#641]
The "Connecting to a Fuel Node" Page has the following text:

-Start Text-
For this interaction to work, the SDK must be able to communicate with a fuel-core node; you have two options at your disposal:

1. Use the [Testnet](https://fuellabs.github.io/fuels-rs/v0.26.0/providers/external-node.html) or run a Fuel node (using fuel-core) and instantiate a provider that points to that node's IP and port.
2. Use the SDK's native launch_provider_and_get_wallet() that runs a short-lived test Fuel node;
The first option is ideal for smart contract testing, as you can quickly spin up and tear down nodes between specific test cases.

For application building, you probably want to go with the second option.
-End Text-

I believe the first option is ideal for application building NOT smart contract testing as the docs state and vis versa.
Let me know if I'm mistaken and this issue should be closed

**Comment by digorithm** [comment]
You're 100% right! This was an editing mistake; we changed the first and second points and forgot to edit the explanation below.
