### ISSUE TITLE
 Build test projects concurrently once `forc` supports it

### ISSUE THREAD

**Issue by hal3e** [FuelLabs/fuels-rs#658]
The code on the SDK side is ready. We only have to change a default value in `buils-test-projects` once `forc` supports concurrent builds.
Issue to track: https://github.com/FuelLabs/sway/issues/2603

**Comment by bingcicle** [comment]
I think this could be attempted again once https://github.com/FuelLabs/sway/pull/3484 is resolved and merged :)

**Comment by hal3e** [comment]
https://github.com/FuelLabs/sway/pull/3592 got merged! Thanks tooling team!
I will update the default number of concurrent projecets.
