### ISSUE TITLE
Support setting external contract dependencies while running scripts that take `main()` arguments

### ISSUE THREAD

**Issue by supiket** [FuelLabs/fuels-rs#667]
Currently, there is no way of setting external contracts while running scripts that take `main()` arguments (#620).
Addition of this feature would unblock [AMM scripts: Swap assets with exact input & swap assets with exact output along a route](https://github.com/FuelLabs/sway-applications/pull/267).

cc: @iqdecay

**Comment by hal3e** [comment]
closed with https://github.com/FuelLabs/fuels-rs/pull/762
