### ISSUE TITLE
Return the readable reason of a revert

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/fuels-rs#679]
# Problem

Consider the following setup: 

```rust
contract;

abi MyContract {
    fn test_function() -> bool;
}

impl MyContract for Contract {
    fn test_function() -> bool {
        require(false, "something is not right");
        true
    }
}
```

And the test file:

```rust
#[tokio::test]
async fn can_get_contract_id() {
    let (instance, _id) = get_contract_instance().await;
    let response = instance.methods().test_function().call().await;
    dbg!(&response);
}
```

Currently, the top-level error will be:

```plaintext
Err(
    RevertTransactionError(
        "Revert(18446744073709486080)"
```

Which tells nothing to the user. If the user manually digs deeper, one of the receipts will be:

```plaintext
LogData {
                id: 0x3d041ddc77907490df673f72cf579763bd7a77ab8e31cf20738f97da7ad225f9,
                ra: 0,
                rb: 0,
                ptr: 11696,
                len: 24,
                digest: 0xd5f441dadfdac1d8f13db35714929fec7c5c9c4cf125cb05d27ff4dcbeb4ba3a,
                data: [
                    115,
                    111,
                    109,
                    101,
                    116,
                    104,
                    105,
                    110,
                    103,
                    32,
                    105,
                    115,
                    32,
                    110,
                    111,
                    116,
                    32,
                    114,
                    105,
                    103,
                    104,
                    116,
                    116,
                    116,
                ],
                pc: 11684,
                is: 11624,
            }
```

That `data` piece is the string `"something is not right"` used in the revert. This should be the top-level error.

# Solution 

We have to find a way to parse that `data` into a string and return it if the contract call reverted. Currently, we have this in `send_transaction`: https://github.com/FuelLabs/fuels-rs/blob/88eb85313f8e5f7fb60c14c6220b9adbf304b845/packages/fuels-signers/src/provider.rs#L81. 

```Rust
 let (status, receipts) = self.submit_with_feedback(&tx.clone().into()).await?;

  if let TransactionStatus::Failure { reason, .. } = status {
      Err(Error::RevertTransactionError(reason, receipts))
  } else {
      Ok(receipts)
  }
```

We have to detect it was a revert. Once that's done, we might have to extend `RevertTransactionError` to include the string representing the error. 

Of course, the actual solution design is up for discussion. Our only goal is to return that string in `LogData.data` after a revert so that users don't have to dig deep to find it.

**Comment by nfurfaro** [comment]
A couple thoughts:
- the receipt that is needed to retrieve the desired top-level error from should be immediately before the `Revert(18446744073709486080)`, which should make it easier to find.
- The custom error _may_ be a string, or it could be any other type. 
I'm often using Enums as custom errors, i.e:
```
require(a != b, MyCustomError::Variant_A);
```
