### ISSUE TITLE
Abigen finds `std::string::String` over sway-lib's `String`

### ISSUE THREAD

**Issue by bitzoic** [FuelLabs/fuels-rs#686]
When attempting to pass or return the sway-libs `String` type, abigen mistakes this for Rust's standard library string.

For example, running a test on the following Sway code generates this error:

```rust
contract;

use sway_libs::string::String;

abi MyContract {
    fn test_get() -> String;
    fn test_set(new_string: String);
}

impl MyContract for Contract {
    fn test_get() -> String {
        String::new()
    }

    fn test_set(new_string: String) {
        
    }
}
```
![strings_test_error](https://user-images.githubusercontent.com/54727135/200388058-449131c3-a663-4922-9b20-1ac0b0066ea8.png)

The Sway-lib's `String` is currently simply a wrapper on Sway's `Vec`:

```rust
pub struct String {
    bytes: Vec<u8>,
}
```

**Comment by segfault-magnet** [comment]
@bitzoic there is a problem with the name collision, so I'll fix that in this task. 

But note that you can't return anything containing a vector until [this](https://github.com/FuelLabs/fuels-rs/issues/602) task is done.

Even then I fear you won't be able to return this as there was an inter-team meeting on which we agreed that returning vectors will be supported only at the topmost level -- i.e. `fn something() -> Vec<Something>`

Even though the nesting of the vec inside Sway's string is superficial (i.e. it will be encoded exactly as a top-level-vec would be), this still might be prohibited by the compiler once the 'vec-as-output' support is done on the Sway side.

@mohammadfawaz fyi.
