### ISSUE TITLE
Handle shared types between different contracts

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/fuels-rs#689]
# Problem

Say the user has two contracts using a shared custom library, and they want to pass data of some custom type (from the shared library) from one contract to another in the SDK. For instance, suppose the following Sway library:

```Rust
library shared_type;

// anything `pub` here will be exported as a part of this library's API
pub struct MyStruct {
    foo: u64,
}
```

And two contracts, `contract_a` and `contract_b`, that look the same, for brevity's sake:

```Rust
contract;

use shared_type::*;

abi MyContract {
    fn takes_shared_type_and_return_it(arg: MyStruct) -> MyStruct;
}

impl MyContract for Contract {
    fn takes_shared_type_and_return_it(arg: MyStruct) -> MyStruct {
        arg
    }
}
```

Then, in the Rust, using the SDK:

```Rust
setup_contract_test!(
    contract_a_instance,
    wallet,
    "packages/fuels/tests/contracts/contract_a"
);

setup_contract_test!(
    contract_b_instance,
    None,
    "packages/fuels/tests/contracts/contract_b"
);

let my_struct = MyStruct { foo: 42 }; 
```

The Rust code above will fail with:

```plaintext
`MyStruct` is ambiguous because of multiple glob imports of a name in the same module consider adding an explicit import of `MyStruct` to disambiguate.
```

That happens because we generate `MyStruct` twice under two different modules: `contract_a` and `contract_b`: 
```Rust
pub mod contractainstance_mod {
            // Imports...
            pub struct contractAInstance {
                contract_id: Bech32ContractId,
                wallet: WalletUnlocked,
                logs_lookup: Vec<(u64, ParamType)>,
            }
            impl contractAInstance {
                pub fn new(contract_id: Bech32ContractId, wallet: WalletUnlocked) -> Self {
                    Self {
                        contract_id,
                        wallet,
                        logs_lookup: ::alloc::vec::Vec::new(),
                    }
                }
                // ...
            }
            pub struct contractAInstanceMethods {
                contract_id: Bech32ContractId,
                wallet: WalletUnlocked,
            }
            impl contractAInstanceMethods {
                #[doc = "Calls the contract's `takes_shared_type_and_return_it` function"]
             // ...
            pub struct MyStruct {
                pub foo: u64,
            }
```

```Rust
pub mod contractbinstance_mod {
            // Imports...
            pub struct contractBInstance {
                contract_id: Bech32ContractId,
                wallet: WalletUnlocked,
                logs_lookup: Vec<(u64, ParamType)>,
            }
            impl contractBInstance {
                pub fn new(contract_id: Bech32ContractId, wallet: WalletUnlocked) -> Self {
                    Self {
                        contract_id,
                        wallet,
                        logs_lookup: ::alloc::vec::Vec::new(),
                    }
                }
                // ...
            }
            pub struct contractBInstanceMethods {
                contract_id: Bech32ContractId,
                wallet: WalletUnlocked,
            }
            impl contractBInstanceMethods {
                #[doc = "Calls the contract's `takes_shared_type_and_return_it` function"]
             // ...
            pub struct MyStruct {
                pub foo: u64,
            }
```

So, two problems arise:
1. The Rust compiler can't disambiguate when you say `MyStruct`; it would have to be `contractainstance_mod::MyStruct`.
2. You can use an instance of `MyStruct`, a shared type, interchangeably between `contract_a` and `contract_b`; `contract_a` takes strictly `contractainstance_mod::MyStruct` and `contract_b` takes strictly `contractbinstance_mod::MyStruct`.

This forces the user to either: 
1. Break Sway best practices (using a library to share types) to please the SDK and the Rust compiler or;
2. Manually disambiguate `MyStruct`s by referring to them as `contractainstance_mod::MyStruct` and `contractbinstance_mod::MyStruct` and when passing `MyStruct` amongst each other, manually creating the other `MyStruct` from the `MyStruct` you have in hands. E.g. `contractainstance_mod::MyStruct { foo: my_original_struct.foo }`.

Both are bad experiences we should come up with some SDK magic to improve this.

# Solution

I haven't thought through any actual solution. Decided to open this issue so we can discuss some options here.

**Comment by segfault-magnet** [comment]
I'll try to summarize what was discussed:

There were two approaches:

Approach 1) Users will call `lib_abigen` manually on all used libraries.
The `mod` names of the generated lib types will be well-known. Contracts that use these types will have their rust bindings redirected to the generated lib types so that they might be shared. The user will need to manually import the library-generated types. Library JSON ABI files would need to be made available. Requires support from the compiler.

Approach 2) Users will pass to `abigen` all related contracts, abigen will proceed to generate bindings with deduplicated/shared types wherever possible. Can be done without compiler support with the caveat that all types will be deduplicated not only the ones coming from a library. 

We've decided to try out approach #2.
