### ISSUE TITLE
Eliminate the use of unsafe block for signing

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/fuels-rs#698]
Related discussion can be found at https://github.com/FuelLabs/sway/pull/3201#discussion_r1008932356

**Comment by Salka1988** [comment]
blocked by https://github.com/FuelLabs/fuel-crypto/pull/36

**Comment by segfault-magnet** [comment]
@Salka1988 is this still blocked?

**Comment by Salka1988** [comment]
> @Salka1988 is this still blocked?

https://github.com/FuelLabs/fuel-crypto/pull/36
`This repository has been archived by the owner on Jan 4, 2023. It is now read-only.`

**Comment by Salka1988** [comment]
There have been minor issues with dependencies which I am currently working on with @leviathanbeak

**Comment by iqdecay** [comment]
Will be fixed by #950 I think

**Comment by Salka1988** [comment]
fixed  by #950
