### ISSUE TITLE
Handle `raw_slice` in the SDK

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/fuels-rs#703]
`raw_slice` is a new type that was introduced in the compiler to allow returning dynamically-sized data from scripts. The idea is that someone could write
```rust
fn main() -> raw_slice {
    // Convert to a vector
    let vec: Vec<u64> = Vec::new();

    vec.push(1);
    vec.push(2);
    vec.push(3);

    // Return it
    vec.as_raw_slice()
}
```
and they would get a `ReturnData` receipt that contains a byte representation of `[1, 2, 3]`.

We recently discussed an option to hide this from users who are testing contracts as follows:

The user writes a contract method that returns `Vec<u64>`:
```rust
fn foo() -> Vec<u64>;
```
From the JSON ABI, it would be clear that this is a vector.

When the SDK creates a script that calls `foo()`, it writes:
```rust
fn main() -> raw_slice {
    ...
    caller.foo().as_raw_slice()
}
```
Note that returning from the contract to the script itself does not need a `raw_slice` since the pointer from the contract is valid in the script, but **not** valid outside the script, hence the need for a `raw_slice`.

With above, users who are testing their contracts never need to think about raw slices, but they would only ever be allowed to return a single vector at a time, which is an annoying but reasonable limitation for the time being.

If we like this direction, I can create a similar issue in `fuels-ts`.

**Comment by iqdecay** [comment]
@mohammadfawaz can you please link to the PR implementing this in `Sway` for more context? I don't seem to be able to find it.

**Comment by mohammadfawaz** [comment]
This is the PR: https://github.com/FuelLabs/sway/pull/3288 cc @AlicanC

**Comment by iqdecay** [comment]
@mohammadfawaz I added support for returning `raw_slice` in scripts in #743. Do you mind creating a separate issue about the SDK supporting contracts calling scripts that return a raw slice? It feels like a different subject to me.

**Comment by mohammadfawaz** [comment]
@iqdecay yup! I will do that asap.

**Comment by mohammadfawaz** [comment]
Created a separate issue here: https://github.com/FuelLabs/fuels-rs/issues/746
