### ISSUE TITLE
Support main arguments in predicates

### ISSUE THREAD

**Issue by hal3e** [FuelLabs/fuels-rs#721]
Currently, we access the data inside predicates using the `input_predicate_data(index: u64)` function. However, the compiler can compile a predicate with main function arguments and generate the appropriate json abi. We could create an `abigen` for predicates that will encode the main function arguments the same way as we are doing it with `scripts`.

This issue is blocked because the compiler expects the data to be in the same place as script data. This should be changed to point to predicate data. However, there are two places where predicate data can be stored `GTF_INPUT_COIN_PREDICATE_DATA`  and `GTF_INPUT_MESSAGE_PREDICATE_DATA`. The compiler can not know beforehand if the input will be a coin or message.

**Comment by mohammadfawaz** [comment]
The compiler is going to introduce a runtime check to compare against `GTF_INPUT_TYPE` to decide whether `GTF_INPUT_COIN_PREDICATE_DATA` or `GTF_INPUT_MESSAGE_PREDICATE_DATA` should be used. Basically replicating the logic in https://github.com/FuelLabs/sway/blob/master/sway-lib-std/src/inputs.sw#L99-L114.

**Comment by mohammadfawaz** [comment]
I have a PR up with the change https://github.com/FuelLabs/sway/pull/3523. I'd like to get feedback on whether this works well in all cases. It's hard to test because our testing infra is not capable of testing predicates without the SDK.

**Comment by hal3e** [comment]
closed in https://github.com/FuelLabs/fuels-rs/pull/726
