### ISSUE TITLE
Add support for the new stdlib type `Bytes`

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/fuels-rs#723]
The PR for this type can be found here: https://github.com/FuelLabs/sway/pull/3454

Related: https://github.com/FuelLabs/fuels-rs/issues/709

**Comment by mohammadfawaz** [comment]
Aside from the usual support for standard library types, this also requires extra considerations, just like `Vec`, because it is a heap type. This, of course, has various implications especially in the ABI.
