### ISSUE TITLE
Methods without `#[payable]` annotation cannot accept coins

### ISSUE THREAD

**Issue by anton-trunov** [FuelLabs/fuels-rs#742]
Once https://github.com/FuelLabs/sway/pull/3450 is merged the SDK also needs to forbid accepting coins in non-payable functions. The current plan is to introduce function attributes into the JSON ABI schema to mark payable functions as such. I'm happy to take any comments/suggestions on this.

Spec issue: https://github.com/FuelLabs/fuel-specs/issues/446
Compiler change: https://github.com/FuelLabs/sway/pull/3450

**Comment by digorithm** [comment]
@anton-trunov could you open the same issue on the TS SDK repo as well (https://github.com/FuelLabs/fuels-ts)?

**Comment by anton-trunov** [comment]
@digorithm Done! https://github.com/FuelLabs/fuels-ts/issues/675
