### ISSUE TITLE
Transform `Vec` return from a contract into a `raw_slice` return from the calling scripts

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/fuels-rs#746]
Say we have the following contract:
```rust
contract;

abi MyContract {
    fn returns_vec() -> Vec<u64>;
}

impl MyContract for Contract {
    fn returns_vec() -> Vec<u64> {
        let mut v:Vec<u64> = Vec::new();
        v.push(1);
        v.push(2);
        v
    }
}
```
The method `returns_vec()` returns a `Vec<u64>` and the JSON ABI contains that information. If the SDK were to try to decode returned data, it will just be looking at a pointer that means nothing outside of the VM memory. Instead, a calling script might do the following:
```rust
fn main() -> raw_slice {
    let caller = abi(MyContract, <contract_id>);
    caller.returns_vec().as_raw_slice()
}
```
I'm proposing that the SDK does this automatically as follows:
1. The SDK knows that the return type _from the contract_ is a `Vec` and knows it element type.
2. The `CALL` opcode will give us back a base pointer (say in `$r1`) and a length (say in `$r2`)  (basically information contained in the struct `Vec`). Instead of returning those values directly and decoding them, we need an extra step that somehow crafts a `retd $r1 $r2` instruction. This instruction will generate a `ReturnData` receipt with all of the actual vector data is included. This is basically what `as_raw_slice()` is doing under the hood, but in a more convoluted manner. 

If we do the above, then the user will seamlessly be able to return vectors from contracts. That still won't work for multiple `Vec` returns (e.g. tuple of vectors), but that's okay for now.

**Comment by iqdecay** [comment]
@mohammadfawaz am I correct in understanding that it would only work for `Vec<u64>`? Or for all `Vec<integer>`? Or it would work with vectors in general?

**Comment by mohammadfawaz** [comment]
All data types should be possible I think. The json ABI tells us everything we need to know about the element type, and the length of the returned data tells us how many elements there are (divide the number of bytes by the size of the element type).

**Comment by chlenc** [comment]
Have the same issue!

**Comment by iqdecay** [comment]
Just realized this is blocked by #757

**Comment by iqdecay** [comment]
Was unblocked a while ago and have been working on this.
