### ISSUE TITLE
abigen: exclude first 3 fields instead of name matching

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/fuels-rs#75]
https://github.com/FuelLabs/fuels-rs/blob/eb0f17c5907cb17b54c302f60283ea4f8f483605/fuels-core/src/code_gen/functions_gen.rs#L139

Currently, only fields with specific names are ignored. This isn't really documented anywhere and is the source of endless confusion. Moreover, currently the compiler requires exactly 4 fields from ABI methods: 3 implicit and one for user parameters. Therefore, there's no reason to prune on matching names when the first 3 can simply be pruned.

**Comment by vnepveu** [comment]
So from my tests: currently, 14 exemples/tests *don't* give these 3 parameters, 9 do. So there are 2 approaches: either you require every example to provide them (annoying) so I change the 14 exemples, or I remove the parameters in the 9 remaining and I don't check for these parameters in the ABI. I'm thinking of going for the latter

**Comment by vnepveu** [comment]
Yes I can do that

**Comment by vnepveu** [comment]
![image](https://user-images.githubusercontent.com/32623452/152360211-a99689a3-c896-4190-a91a-58cdea181be0.png)
Would that kind of approach suit you? And then I can propagate this `strict_checking` back to the macro def.

**Comment by adlerjohn** [comment]
> without resorting to name matching haha

Couldn't you just check the types of the first 3 args?

**Comment by vnepveu** [comment]
Ah yes sure

**Comment by adlerjohn** [comment]
This is 1) a temporary thing until the compiler is improved and 2) users will always use ABI generated from the compiler. The only time where this implicit convention would be an issue is internally, but internally we just don't use the abigen flavor that removes the first 3 parameters (except to test that it works correctly of course).
