### ISSUE TITLE
Add section in the docs for transaction dependencies estimation

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/fuels-rs#754]
We now support tx dependencies estimation, but looks like the docs don't mention it. We should add a section for it.

**Comment by mohammadfawaz** [comment]
Yup! Noticed this today when I was answering [this question](https://forum.fuel.network/t/when-should-append-message-outputs-be-used-and-when-should-append-variable-outputs-be-used/1062) and had to look at some tests to figure out the syntax.
