### ISSUE TITLE
Develop a way to expand `inputs` and avoid duplicates

### ISSUE THREAD

**Issue by Salka1988** [FuelLabs/fuels-rs#758]
When we request `get_asset_inputs_for_amount` from the node, we'll get resources of the node's choosing following a randomized algorithm to prevent dust accumulation.

During the formation of our tx we ask for resources to cover the gas fee and cover whatever assets the contract calls required. The node is free to return whichever resources it deems appropriate to cover our request.

Later on, after we've formed the tx, somebody might want to add some more inputs for whatever reason. They're probably going to do that using extend_inputs. And they're probably going to get those inputs by calling `get_asset_inputs_for_amount`.

There is nothing (AFAIK) preventing the possibility that the node is going to return resources that we've already 'reserved' by either covering the transaction costs or because a contract call demanded them. The node can't know we're planning to do anything with the resources it had suggested just a few moments before while we were building the tx.

So a user might find this snippet to work most of the time:

```rust
let mut a_call = contract.methods().some_method().get_executable_call();
let some_more_inputs = wallet.get_asset_inputs_for_amount(...);
a_call.extend_inputs(some_more_inputs);
```

but once in a while, the node will return a resource we've already placed in our tx inputs and then this code will error out due to the duplicated ids. This is problematic.

We could either:

1- leave the user to his own devices and have him request all his resources and filter out the ones we've already chosen for his tx, or repeat get_asset_inputs_for_amount until the node changes its mind, or,
2- develop a way of extending inputs such that we request resources from the node only once for a given asset id.
    both of the above, let the user use the error-prone one if he knows what he's doing

The `#1` way is more flexible because the user would choose exactly which resource he wants to extend as inputs. I'm out of my depth here but that could be used to make decisions in the contract? Heard about predicates making decisions based on inputs.

The  `#2` way is more friendly, just have the user extend the inputs by noting his wish of (asset_id, amount) and we'll find the coins for that wish and for our other needs at the same time, avoiding duplicates.
So something like:
```rust
call.add_input_resources(asset_id, amount);
```
and right before executing the script, we would do one pass per asset id to actually find all the needed resources.

**Comment by Salka1988** [comment]
Obsolete!

**Comment by iqdecay** [comment]
@Salka1988 I don't think this is obsolete, @MujkicA IIRC we agreed that there was some extra steps needed to avoid duplicates in #778
