### ISSUE TITLE
Devx for `low_level_call` usage from the sway stdlib

### ISSUE THREAD

**Issue by segfault-magnet** [FuelLabs/fuels-rs#775]
[`low_level_call`  in the sway std lib](https://github.com/FuelLabs/sway/blob/770b0ec416f2dcb9ed37f1465ef1bb405af28210/sway-lib-std/src/low_level_call.sw) (Note, not yet merged ATTOW)

Calling a contract is done via the [`CALL` instruction](https://fuellabs.github.io/fuel-specs/master/vm/instruction_set.html#call-call-contract). 

Currently, when users want to call a contract method, we'll create a script with a `CALL` instruction and the data into which the instruction registers point.

Now, the sway stdlib has a function (currently called [ `call_with_function_selector` ](https://github.com/FuelLabs/sway/blob/770b0ec416f2dcb9ed37f1465ef1bb405af28210/sway-lib-std/src/low_level_call.sw#L80) and [`call_with_raw_payload`](https://github.com/FuelLabs/sway/blob/770b0ec416f2dcb9ed37f1465ef1bb405af28210/sway-lib-std/src/low_level_call.sw#L41) which, although private currently, might also be exported) which is expected to be used by our users while writing their contracts.

This means that we're probably looking at improving the devx of preparing the data for the `CALL` instruction so that it may be given to the contract method which in turn gives it to the `CALL` instruction via the helpers in the `low_level_call` library.

Currently, the code doing this is private (`pub(crate)`) and not meant to be used directly by our users. Also, it is intimately coupled with our internal abstractions (i.e. `ContractCall` and other structures).

With the help of the app-dev team (and @simonr0204 who is working on this), we're to figure out the best experience for supporting this workflow.

Some of the key points might be:
* how will our users get the function selector? 

By letting them manually populate the args for [`resolve_fn_selector`](https://github.com/FuelLabs/fuels-rs/blob/ac70a466a4764e22ab97a550c406386a8b0153b5/packages/fuels-core/src/code_gen/function_selector.rs#L7) ? 

Or having them use the `JSON` abi to convert the function into `ParamTypes` first via [`ParamType::try_from_type_application`](https://github.com/FuelLabs/fuels-rs/blob/ac70a466a4764e22ab97a550c406386a8b0153b5/packages/fuels-types/src/param_types.rs#L108)?

Will we store the function selector during the `abigen!` process? So that the users might just extract it from the function they wish to call? 
* How will we handle vectors/offsets?

Are we sure we can calculate the memory location into which the SDK-generated payload is going to be loaded into? 
What can the receiving contract do with the payload? What can cause the pointers inside the payload to become invalid? 

And probably other considerations I can't think of off the top of my head.

Also [take a look at a macro](https://github.com/FuelLabs/sway/pull/3742/files#diff-db0ccd9b49fdfeb6ec7808ec252d7ce2f302d530f45fc0b448938a363f63f0faR148-R155) I threw together to lessen the pain during the testing of this feature. 

Do we want to have the SDK support something like this? Is it redundant? And much much more :)

**Comment by simonr0204** [comment]
From a devex perspective, the ultimate would be to leverage the existing contract API, so something like:

```
let payload = callee_instance.methods().is_low_level_called(my_args).raw_payload();
```

where `payload` would end up being the encoded `target_contract_id ++ function_selector ++ encoded_calldata` that can be directly passed through to `CALL(r1, r2, r3, r4)` (as `r1`).

The problem with this, as I understand it, is that the offsets used when generating the payload for the _callee_ contract depend on the exact ordering of the args in the _caller_ contract. i.e.

`caller_instance.methods().makes_a_low_level_call(param1, param2, calldata)`
would have different offsets to
`caller_instance.methods().makes_a_low_level_call(calldata, param1, param2)`

**Comment by segfault-magnet** [comment]
@Braqzen also has a similar use-case.

He has a struct containing a vector. The struct is not part of a Contract/Script ABI, thus not abi-generated.

Since the offset resolving is not public, he has no way of getting the encoded payload.

The unique twist to @Braqzen use case is that he would not have the bindings generated and thus a solution making use of `methods().` and anything related to that would not work for him.

**Comment by segfault-magnet** [comment]
Might be related: https://github.com/FuelLabs/fuels-rs/issues/709
