### ISSUE TITLE
Name collision on types of different contracts 

### ISSUE THREAD

**Issue by supiket** [FuelLabs/fuels-rs#791]
Example scenario:

_Contract 1_ [imports an enum `AccessError`](https://github.com/FuelLabs/sway-applications/blob/supiket/bump/NFT/project/NFT-contract/src/main.sw#L8). 
This contract [imports _contract 2_](https://github.com/FuelLabs/sway-applications/blob/supiket/bump/NFT/project/NFT-contract/src/main.sw#L26) which in turn [imports a different enum with the same name](https://github.com/FuelLabs/sway-libs/blob/master/libs/nft/src/nft_core.sw#L7).

This results in the following error when using `abigen!` with _contract 1_:
```
the name `AccessError` is defined multiple times
`AccessError` must be defined only once in the type namespace of this module
```

**Comment by segfault-magnet** [comment]
Blocked by https://github.com/FuelLabs/sway/issues/4235
