### ISSUE TITLE
Feature request: Add support for the new `assert_eq`

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/fuels-rs#799]
I'm adding a new function in `std::assert` called `assert_eq` which will male use of a new error code found [here](https://github.com/FuelLabs/sway/blob/e7a74665615123cd3276a1e9905a4fc7fe1d4040/sway-lib-std/src/error_signals.sw#L18).

The SDK support needed will consist of the ability to:

- recognize the revert error (the same way the SDK handles the error for a failed `require`
- log the values of the 2 previous `log` or `logd` receipts in a presentable way, perhaps following the rus example of "lhs != rhs"

**Comment by hal3e** [comment]
Is there a `sway` PR that we can track here ?

**Comment by nfurfaro** [comment]
@hal3e there will be shortly; I will drop a link here as soon as I open it. Just working on the tests.

**Comment by hal3e** [comment]
Blocked until https://github.com/FuelLabs/sway/issues/3946 is fixed.
