### ISSUE TITLE
Sway `timestamp()` seems to not be shifted by `produce_blocks()`

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/fuels-rs#849]
[Here](https://github.com/Braqzen/tmp_timestamp) is a link to the repro.

It makes a call to some function which logs the time, the SDK shifts some blocks at some interval of time and calls the same function again to log the new timestamp. The timestamp printed to the standard output is the same.

**Comment by segfault-magnet** [comment]
@iqdecay was this solved by the client fix? I.e. should we close the issue now?

**Comment by iqdecay** [comment]
[Upstream fix](https://github.com/FuelLabs/fuel-core/pull/1059)

**Comment by FossilFrank** [comment]
Now that FuelLabs/fuel-core#1059 is merged & included in fuel-core 0.18.0, is this issue resolved? Or are there changes that need to go into the Rust SDK?

**Comment by Braqzen** [comment]
> Now that [FuelLabs/fuel-core#1059](https://github.com/FuelLabs/fuel-core/pull/1059) is merged & included in fuel-core 0.18.0, is this issue resolved? Or are there changes that need to go into the Rust SDK?

Sorry, should have responded earlier. The SDK needs to implement support for this change from what I recall as the client has resolved this issue some time ago. @iqdecay can elaborate on this more as they are working on this.

**Comment by iqdecay** [comment]
The new release of `fuel-core` should indeed fix this. However, some adaptation from the SDK to `fuel-core 0.18` is needed first. This adaptation is tracked in #933. After that, a few lines of codes are needed so the SDK experience is good, those lines are ready.

**Comment by iqdecay** [comment]
This was definitely fixed in #950. In addition, a proper example will come with #985.
