### ISSUE TITLE
test: implement test for logging `Vec<>` in the SDK 

### ISSUE THREAD

**Issue by iqdecay** [FuelLabs/fuels-rs#861]
Currently vector logging is not tested

**Comment by hal3e** [comment]
AFAIK we can not directly decode a `Vec` log as the log data holds only the `pointer`, `length` and `capacity`. Is the sway team going to change logging for `Vec`s ?

**Comment by iqdecay** [comment]
Ah you're right actually! It's just that in the original issue I had seen logging but it's not currently possible.
