### ISSUE TITLE
feat: support heap types return from scripts

### ISSUE THREAD

**Issue by iqdecay** [FuelLabs/fuels-rs#866]
#848  introduced `Vec<>` type return from contracts, the same should be done for scripts.
#868  introduced `Bytes` type return from contracts, the same should be done for scripts.

**Comment by Dhaiwat10** [comment]
@iqdecay we need to implement this on the TS SDK, too. Can you pls share any issues that you are tracking on the compiler so that we know when the support is there?

**Comment by hal3e** [comment]
done in: https://github.com/FuelLabs/fuels-rs/pull/1303
