### ISSUE TITLE
Add initial storage slots in the SDK automatically based on compiler output

### ISSUE THREAD

**Issue by vnepveu** [FuelLabs/fuels-rs#87]
# Tasks

- [x] https://github.com/FuelLabs/sway/issues/1185: wait for this to be finished
- [ ] Read the new [storage file being outputted by the compiler](https://github.com/FuelLabs/fuel-specs/blob/master/specs/protocol/storage_initialization.md) and set the initial storage slots in the contract creation transaction

**Comment by MujkicA** [comment]
Blocked by #441 since the introduction of automatic initial slots needs to consider overlapping keys that may have been added manually
