### ISSUE TITLE
feat: support `RawSlice` as argument

### ISSUE THREAD

**Issue by iqdecay** [FuelLabs/fuels-rs#878]
Not sure if Sway supports it though. 
From @segfault-magnet :

I tried implementing RawSlice support, turns out it isn't difficult.

A RawSlice is encoded as two u64 ptr and len. So encoding it would look like this:

    fn encode_raw_slice(data: &[u64]) -> Result<Vec<Data>> {
        let tokens = data
            .iter()
            .map(|&word| word.into_token())
            .collect::<Vec<_>>();
        let encoded_data = Self::encode_tokens(&tokens)?;
        let len = data.len() as u64 * 8;
        Ok(vec![Data::Dynamic(encoded_data), Self::encode_u64(len)])
    }

the function selector is rawslice.

ParamType::try_from_type_application needs to be updated to detect raw slices. This helper is used by the index team to generate fn selectors in runtime from only the json abi file.

Its encoding width is 2 WORDS, so compute_encoding_width needs to be updated.

Also, you need to add it to should_compute_custom_input_offset.

That's all you need to nest raw slices however deep in other types when used as function arguments.

**Comment by segfault-magnet** [comment]
> Not sure if Sway supports it though. 

I figured out the encoding by doing examples in Sway. So passing in raw slices definately works if you're referring to that.

Didn't try nesting it though in inputs, but I nested it in a tuple and returned it and the compiler didn't complain.

Have a feeling if that passed so will nesting when used in fn args

**Comment by iqdecay** [comment]
Closed by #904.
