### ISSUE TITLE
Connect contract instance to existing contract

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/fuels-rs#88]
Currently, we're only able to create a contract instance by compiling and deploying it: 

```rust
let contract_instance = MyContract::new(compiled, client);
```

We should be able to create a contract instance from an already deployed contract by referencing to its deployed address, similar to `ethers.js` / `ethers-rs`. Something similar to this:

```rust
 let contract_instance = MyContract::connect("0x...");
```

**Comment by adlerjohn** [comment]
Does this not require something like a block explorer with an API? Or is it possible to connect to a deployed contract against a local node if you know the contract code and salt (or potentially just contract code root and salt, and the JSON ABI)?

**Comment by digorithm** [comment]
> Does this not require something like a block explorer with an API? Or is it possible to connect to a deployed contract against a local node if you know the contract code and salt (or potentially just contract code root and salt, and the JSON ABI)?

Yeah, I believe the latter is possible, similar to the Solidity dev workflow:

```js
let contractAddress = "0x2bD9aAa2953F988153c8629926D22A6a5F69b14E";

let contract = new ethers.Contract(contractAddress, abi, provider);
```

Not exactly like that, but _something_ like that. Interacting with already deployed contracts seems to be a common thing and I believe `fuels-rs` should support that.

**Comment by nfurfaro** [comment]
Highly agree. It's a fairly common task (in ethers.js at least) to Interact with a deployed contract using the address and abi.
