### ISSUE TITLE
Remove backward compatibility for ABI custom types without paths

### ISSUE THREAD

**Issue by segfault-magnet** [FuelLabs/fuels-rs#881]
Currently, type-paths are feature-gated behind the `forc` flag `--json-abi-with-callpaths`. 

Once the TS SDK implements support for type paths, `forc` will make this behavior default. 

We can then remove the backward compatibility code from `fuels-rs`. Most, if not all of the places that should be looked at have a `TODO` referencing this issue.

**Comment by hal3e** [comment]
Is there an issue on the TS side that we can track ?

**Comment by hal3e** [comment]
Issue to track on the ts side: https://github.com/FuelLabs/fuels-ts/issues/2162
