### ISSUE TITLE
Transactions getting rejected due to "UTXO does not exist"

### ISSUE THREAD

**Issue by MujkicA** [FuelLabs/fuels-rs#903]
Transactions on the beta network will occasionally be rejected with the following reason "UTXO does not exist". 

One possible cause could be that resources_to_spend API is returning coins that have already been included in other transactions they've submitted (due to the delay between submitting a transaction and marking the inputs as spent). 

If the cause is confirmed to be the above, we can consider the following solution suggested by @Voxelot:

The SDK should maintain a cache of recently used UTXOs, which are to be excluded calling resources_to_spend. When a transaction is confirmed or rejected, these UTXOs can be removed from the cache. This may require users to wait for their change outputs to become available before making subsequent transactions, but the process can be optimized by spending the change outputs of pending transactions in-flight. The SDK can predict the change outputs of previously submitted transactions during dry-run, which can aid in selecting pending outputs.

**Comment by diyahir** [comment]
Yes, please fix this, I've been running into the same issue I am manually wrapping my calls with a 

try {}
catch { try_again }

which is far from ideal

**Comment by digorithm** [comment]
Resolved.
