### ISSUE TITLE
deps: bump `fuel-core` to `0.18` and `fuel-*` to `0.31`

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/fuels-rs#933]
We have the sway repo bump here here:

https://github.com/FuelLabs/sway/pull/4428

But I think I am blocked on it since we don't have a SDK release which supports latest the [fuel-vm repo](https://github.com/FuelLabs/fuel-vm) crates: (fuel-vm, fuel-tx, fuel-asm etc).

**Comment by iqdecay** [comment]
Blocked until a new release of `fuel-core`.

**Comment by iqdecay** [comment]
Unblocked, working on it

**Comment by iqdecay** [comment]
Closed by #950
