### ISSUE TITLE
Error 'could not retrieve ScriptResult' when calling contract on Beta-3 testnet

### ISSUE THREAD

**Issue by diyahir** [FuelLabs/fuels-rs#939]
I'm running a script to initialize many smart contracts, at random points in the deployment it will produce this error:
'panicked at 'could not retrieve ScriptResult''

Since I need to initialize 8 contracts, running it a few times with the hopes that it doesn't randomly produce this issue is not an option. I can successfully deploy/upload the contracts, only when it's time to call the initialize function on them does it break. I am using Beta-3 Fuel testnet on this script, but I also have local tests that never break when running the same code

I believe this is an error with Beta-3 either timing out, or bugging out after successive smart contract calls (though I have await statements wrapping the calls)

**Comment by iqdecay** [comment]
Hey, can you please provide a code example if it's not too hard? After checking, I do think it's a problem with the client rather than the SDK, but some code would help to make sure of that.

**Comment by diyahir** [comment]
Upgraded packages, and no longer an issue

**Comment by diyahir** [comment]
Jk it's back

`let tx_params = TxParameters::default().set_gas_price(1);

        let res = manager
            .methods()
            .initialize(admin)
            .tx_params(tx_params)
            .call()
            .await
            .unwrap();

        return res;`

it basically break in these initialization contract calls when going through beta-3

**Comment by iqdecay** [comment]
We're looking into this. The most likely culprit is, as I said before, the client's response, that would IMO not contain the receipts the SDK expects to.

**Comment by Br1ght0ne** [comment]
@diyahir As @iqdecay mentioned before, could you please provide a minimal reproducible example for me?
