### ISSUE TITLE
deps: change the `forc` version in CI after a new release supports `fuel-core 0.18`

### ISSUE THREAD

**Issue by iqdecay** [FuelLabs/fuels-rs#954]
- Also re-enable `low_level_calls` tests
- Remove the `std` deps from `Forc.toml` in tests

**Comment by digorithm** [comment]
Once https://github.com/FuelLabs/sway/pull/4525 is merged, our tests will fail, as many reference sway's `feature/fuel-core-0.18` branch, which will be auto-deleted upon merge.

**Comment by iqdecay** [comment]
Closed by #988.
