### ISSUE TITLE
Support `fuels --no-default-features` not including `fuel-tx`'s default dependencies

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuels-rs#970]
### Description
- I believe `fuels` is pulling in `fuel-tx` with its default features, which include `getrandom` in the `fuel-types` branch of the dependency tree 
- We should allow the use of `fuels --no-default-features`, without automagically including the default dependencies of `fuel-tx`

### Reproduce 
- `cargo new --lib foo`
- Add `fuel-tx = { version = "0.26", default-features = false }` to your manifest. Compile. Shouldn't see any reference to `getrandom`
- Add `fuels = { version = "0.40", default-features = false }` to your manifest. Compile. Should see a reference to `getrandom`

### Desired Result
- If at all possible to _not_ include any references to `getrandom` that would be ideal 👌🏽

**Comment by Br1ght0ne** [comment]
If I understand correctly, the dependency branch in question is `fuels - fuel-tx - fuel-asm - fuel-types - rand - getrandom`. At no point in this chain there are feature flags governing the usage—everything is brought in by default. E.g., making `fuels` depend on `fuel-tx = { default-features = false }` does *not* remove `getrandom` from the tree. Additional feature flag changes on `fuel-vm` side are required.

**Comment by ra0x3** [comment]
@Br1ght0ne 
- Thanks, I agree with what's mentioned
- I've opened up a fuel-vm issue https://github.com/FuelLabs/fuel-vm/issues/448
- I'd like to keep this (fuels-rs) issue open until the fix in fuel-vm is confirmed and merged 🙏🏽

**Comment by xgreenx** [comment]
The `fuel-tx 0.31` [should work](https://github.com/FuelLabs/fuel-vm/issues/448#issuecomment-1551285523) with `default-features = false`.

**Comment by ra0x3** [comment]
@xgreenx 
- Thanks for that
- Do you think we'd just have to wait til the SDK updates `fuel-tx` ?
- We're currently on `fuels 0.40` and `fuels 0.40` is using `fuel-tx 0.26`
- Are you saying it might be easier to just wait til `fuels` updates to `fuel-tx 0.31` then try again?

**Comment by xgreenx** [comment]
If you want to solve the issue as soon as possible, you can try to use the branch from https://github.com/FuelLabs/fuels-rs/pull/950. It uses `fuel-tx 0.31` and `fuel-core 0.18`. If you find some issues with a new version, we can patch it easily and create a new release. It would be simpler for us and faster for you=)

**Comment by ra0x3** [comment]
Thanks I'll see if I can use that branch as a temporary workaround =)

**Comment by Br1ght0ne** [comment]
As #950 was merged, seems like this is no longer a problem.
You are welcome to reopen if otherwise @ra0x3
