### ISSUE TITLE
Remove `launch_and_deploy` function, refactor launching node

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/fuels-rs#98]
The `launch_and_deploy()` function is generally messy and confusing because it conflates two things: launching a node and deploying a contract.

https://github.com/FuelLabs/fuels-rs/blob/f02c231bde373466fc94237cd77134e00114726d/fuels-contract/src/contract.rs#L223-L236

It also makes writing tests more brittle and non-uniform, e.g. if you deploy two contracts for a single test, the second contract has to use `deploy`. Then if you rearrange things to deploy the second contract first, all of a sudden your test will break.

## Action

- [ ] Remove `launch_and_deploy()`.
- [ ] Add a new function `launch()` that launches a new node with the provided configuration (e.g. port, and genesis state), so long as there's not a node already running at that port. When done, the node should be shut down.
- [ ] Maybe add a new function `connect()` that connects to an already-running node. When done, the node should not be shut down. Can be left to a future issue.

**Comment by digorithm** [comment]
I have an upcoming PR that will introduce the provider abstraction, which will encapsulate the FuelClient. So the third point, connecting to an already running node, will be resolved by it. All you'll need to do is instantiate a new provider passing the URL of the running node and the subsequent network calls will go through it.
