### ISSUE TITLE
Better handle generated custom types that are equivalent between Sway and `fuel_types`

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/fuels-rs#99]
# Motivation 

In cases where a Sway contract is using the `stdlib`'s native structs such as:

```rust
use std::{address::Address, contract_id::ContractId};

pub struct ParamsGetBalance {
    target: b256,
    asset_id: ContractId,
}
```

the SDK's `abigen!` will generate these as custom structs:

```json
{
    "components": [
        {
            "components": null,
            "name": "value",
            "type": "b256"
        }
    ],
    "name": "asset_id",
    "type": "struct ContractId"
}
```

```rust
 pub struct ContractId {
    pub value: [u8; 32],
}
```

And, then, when using it in the SDK:

```rust
#[tokio::test]
async fn mint() {
    let salt = get_new_salt();

    abigen!(TestFuelCoinContract, "test_projects/token_ops/src/abi.json",);

    let compiled = Contract::compile_sway_contract("test_projects/token_ops", salt).unwrap();

    let (client, fuelcoin_id) = Contract::launch_and_deploy(&compiled).await.unwrap();

    let fuel_coin_instance = TestFuelCoinContract::new(compiled, client);

    let c = testfuelcoincontract_mod::ContractId {
        value: fuelcoin_id.into(),
    };

    let default_balance_params = ParamsGetBalance {
        target: fuelcoin_id.into(),
        asset_id: c,
    };

    let balance_result = fuel_coin_instance.get_balance(default_balance_params);

    let result = fuel_coin_instance.mint_coins(11).call().await.unwrap();
}
```

Note that you have to reference the generated `ContractId` through its namespace: `testfuelcoincontract_mod::ContractId`. But, underneath, it's equivalent to `fuel_types::ContractId`: they're `[u8; 32]`;

This works fine, but it would be more ergonomic if we treated Sway's `ContractId` (and `Address`) as `fuel_types::ContractId`. So that we could eliminate this conversion step:

```rust
 let c = testfuelcoincontract_mod::ContractId {
    value: fuelcoin_id.into(),
};
```

And simply use `fuelcoin_id: fuel_types::ContractId` to a contract method that takes the Sway's `ContractId`.

# Potential solution 

The `abigen!` process would have to detect that the Sway type being generated is named as `ContractId` (and others such as `Address`) and allow for `fuel_types::ContractId` to be used instead. This require significant changes to the `abigen!` macro.

For instance, this is the generated code when there's a `ContractId` in the custom types:

```rust
 pub struct ContractId {
    pub value: [u8; 32],
}
impl ContractId {
    pub fn param_types() -> Vec<ParamType> {
        let mut types = Vec::new();
        types.push(ParamType::B256);
        types
    }
    
    pub fn into_token(self) -> Token {
        let mut tokens = Vec::new();
        tokens.push(Token::B256(self.value));
        Token::Struct(tokens)
    }
    
    pub fn new_from_tokens(tokens: &[Token]) -> Self {
        Self { value : < [u8 ; 32] > :: from_token (tokens [0usize] . clone ()) . expect ("Failed to run `new_from_tokens()` for custom struct, make sure to pass tokens in the right order and right types") , }
    }    
}

impl fuels_core::Detokenize for ContractId {
    fn from_tokens(
        mut tokens: Vec<Token>,
    ) -> Result<Self, fuels_core::InvalidOutputType> {
        let token = match tokens.len() {
            0 => Token::Struct(::alloc::vec::Vec::new()),
            1 => tokens.remove(0),
            _ => Token::Struct(tokens),
        };
        Ok(ContractId::new_from_tokens(&[token]))
    }
}
```

There are many correct approaches to change this section to use `fuel_types::ContractId` instead. Part of the resolution of this issue is deciding which approach to use.

**Comment by nfurfaro** [comment]
This is something I'm able to work around for now while writing tests, but the more contracts involved in a test, the more cumbersome this gets.
For example, in the following snippet, I'm interacting with 2 contracts, and as a result I need the same `ContractId`(`context_id`) defined in 3 different ways (one under the namespace of each contract and 1 using `fuel_types::ContractId`);
```rust
    let context_id = Contract::deploy(&compiled, &client).await.unwrap();
    let ctx = testcontextcontract_mod::ContractId { value: context_id.into() };
    let ctx2 = testcontextcallercontract_mod::ContractId { value: context_id.into() };

    caller_instance.call_get_this_balance_with_coins(send_amount, ctx2).set_contracts(&[context_id]).call().await.unwrap();

    let result = context_instance
        .get_this_balance(ctx)
        .call()
        .await
        .unwrap();
```

**Comment by adlerjohn** [comment]
The lack of this is actually a pretty big sore spot as an SDK user.

**Comment by digorithm** [comment]
It truly is, can't wait to tackle this one. If only we had more bandwidth... :-)
